version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      open-pull-requests-limit: 0
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '09:00'
          timezone: 'America/Sao_Paulo'
      commit-message:
          prefix: 'chore'
          prefix-development: 'chore'
          include: 'scope'
