import type { SetupContext } from '../context';

export function generatePrePushHook(ctx: SetupContext): string {
    return `#!/bin/sh
# QA Tools pre-push hook — generated by setup/main.ts
# Execute batch mode before push, block if failures found.
# To bypass: git push --no-verify

echo "🔍 QA Tools: Running pre-push checks..."
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

npx tsx git_triggers/main.ts --batch --project ${ctx.projectName} --branch "$CURRENT_BRANCH" --run-impacted-tests &&
npx tsx scripts/quality-gate.ts
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ QA Tools: Pre-push checks failed. Push blocked."
    echo "   Fix the issues or use 'git push --no-verify' to bypass."
    exit 1
fi

echo "✅ QA Tools: All pre-push checks passed."
exit 0
`;
}
