image: node:lts

cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
        - node_modules/

test:
    stage: test
    script:
        - npm ci
        - npm run typecheck
        - npm run test:coverage
