import { defineConfig } from 'vitest/config';
import VitestCtrfReporter from './shared/vitest-ctrf-reporter.js';

export default defineConfig({
    test: {
        globals: true,
        environment: 'node',
        reporters: ['default', new VitestCtrfReporter()],
        setupFiles: [],
        exclude: ['**/node_modules/**'],
        testTimeout: 15000,
        hookTimeout: 30000,
        teardownTimeout: 5000,
        coverage: {
            provider: 'v8',
            exclude: [
                '**/types/**',
                '**/types.ts',
                '**/__mocks__/**',
                '**/*.test.ts',
                '**/*.spec.ts',
                '**/index.ts',
                '**/*-validator.ts',
                '**/*-generator.ts',
                '**/e2e/**',
                'scripts/smartwizard-llm.ts',
                'scripts/smartwizard-discovery.ts',
                'shared/config.ts',
                'shared/env-utils.ts',
                'shared/prompt.ts',
                'shared/prompt-input.ts',
                'shared/prompt-ui.ts',
                'jira_management/import-prep.ts',
                'git_triggers/main.ts',
                'git_triggers/batch-mode.ts',
                'git_triggers/cli-args.ts',
                'git_triggers/interactive-mode.ts',
                'git_triggers/ui-helpers.ts',
                'git_triggers/session-state.ts',
                'git_triggers/import-loop.ts',
                'shared/session-context.ts',
                'scripts/coverage-registry.ts',
            ],
            thresholds: {
                lines: 90,
                functions: 91,
                branches: 80,
                statements: 90,
            },
        },
    },
});
