/**
 * AI Effectiveness Dashboard — HTML rendering layer.
 *
 * Receives computed AiEffectivenessResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module ai-effectiveness-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { icon } from '../icons.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { rootLogger } from '../logger.js';
import {
    MetricCard,
    MetricGrid,
    DataTable,
    Section,
    EmptyState,
    RecommendedActions,
    TrendChart,
} from '../primitives/index.js';
import type { TableColumn, TableRow } from '../primitives/index.js';
import type { AiMetricsResult } from '../types/data-hub-extensions.js';

const ACCEPTANCE_RATE_TARGET = 80;
const MIN_SAMPLE_SIZE = 30;

export function generateAiEffectivenessHtml(result: AiMetricsResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            rootLogger.error(
                'AI effectiveness result is null or undefined. Verify that AI feedback data is being collected and passed correctly.',
            );
            return buildErrorPage('Error generating dashboard', 'Invalid or missing AI effectiveness data');
        }
        const pageTitle = title || 'AI Effectiveness Dashboard';

        if (result.totalRecords === 0) {
            return buildHtmlPage({
                title: pageTitle,
                styles: buildCss(),
                theme: 'system',
                bodyContent: Container(
                    pageTitle,
                    EmptyState({
                        title: 'No AI generation data available',
                        description:
                            'No AI-generated test records were found. This dashboard requires test data produced by the AI generation pipeline.',
                        action: 'Run the AI generation pipeline to produce test data, then regenerate this report.',
                    }),
                    result.timestamp,
                ),
                footer: `Generated by QA Tools — ${pageTitle}`,
            });
        }

        const bodyContent = Container(
            pageTitle,
            buildMetricSummary(result) +
                buildVersionTable(result.byVersion, result.topPromptVersion) +
                buildTrendChart(result.trend) +
                buildActions(result),
            result.timestamp,
        );

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: `Generated by QA Tools — ${pageTitle}`,
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error(
            'Failed to generate AI effectiveness dashboard: ' +
                msg +
                '. Verify that AI feedback data contains valid acceptanceRate, byVersion, and trend fields.',
        );
        return buildErrorPage(
            'Error generating dashboard',
            'An error occurred while generating the AI effectiveness dashboard. Check the logs for details and ensure your AI feedback data is valid.',
        );
    }
}

function Container(pageTitle: string, children: string, timestamp: string): string {
    return `<div data-component="container" data-dashboard="ai-effectiveness">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        <div data-part="timestamp">${sanitizeHtml(timestamp)}</div>
        ${children}
    </div>`;
}

function buildMetricSummary(result: AiMetricsResult): string {
    const { acceptanceRate, totalRecords, totalModified, totalDeleted, topPromptVersion } = result;

    // Determine severity based on acceptance rate
    let acceptanceSeverity: 'success' | 'warn' | 'error';
    if (acceptanceRate >= ACCEPTANCE_RATE_TARGET) {
        acceptanceSeverity = 'success';
    } else if (acceptanceRate >= 50) {
        acceptanceSeverity = 'warn';
    } else {
        acceptanceSeverity = 'error';
    }

    // Calculate modification rate for context
    const modificationRate = totalRecords > 0 ? Math.round((totalModified / totalRecords) * 100) : 0;
    const modificationSeverity = modificationRate > 30 ? 'warn' : 'default';

    // Deleted rate and severity
    const deletedRate = totalRecords > 0 ? Math.round((totalDeleted / totalRecords) * 100) : 0;
    let deletedSeverity: 'error' | 'warn' | 'default';
    if (deletedRate > 20) {
        deletedSeverity = 'error';
    } else if (deletedRate > 10) {
        deletedSeverity = 'warn';
    } else {
        deletedSeverity = 'default';
    }

    // Sample size warning
    const sampleWarning =
        totalRecords < MIN_SAMPLE_SIZE
            ? `Low sample size (${totalRecords}/${MIN_SAMPLE_SIZE}) — results may not be statistically significant.`
            : undefined;

    // Determine sample size severity
    const sampleSizeSeverity = totalRecords < MIN_SAMPLE_SIZE ? 'warn' : 'info';

    return Section({
        dataSection: 'summary',
        title: 'Summary',
        children: MetricGrid({
            children:
                MetricCard({
                    label: 'Acceptance Rate',
                    value: `${acceptanceRate}%`,
                    severity: acceptanceSeverity,
                    target: `target: ${ACCEPTANCE_RATE_TARGET}%`,
                    sampleWarning,
                }) +
                MetricCard({
                    label: 'Total Records',
                    value: String(totalRecords),
                    severity: 'info',
                }) +
                MetricCard({
                    label: 'Modified',
                    value: `${totalModified} (${modificationRate}%)`,
                    severity: modificationSeverity,
                    target: 'target: <30%',
                }) +
                MetricCard({
                    label: 'Deleted',
                    value: `${totalDeleted} (${deletedRate}%)`,
                    severity: deletedSeverity,
                    target: 'target: <10%',
                }) +
                MetricCard({
                    label: 'Top Version',
                    value: sanitizeHtml(topPromptVersion) || 'N/A',
                    severity: 'info',
                }) +
                MetricCard({
                    label: 'Sample Size',
                    value: String(totalRecords),
                    severity: sampleSizeSeverity,
                    target: `min: ${MIN_SAMPLE_SIZE}`,
                    sampleWarning,
                }),
        }),
    });
}

function buildVersionTable(
    byVersion: Array<{ version: string; count: number; acceptanceRate: number }>,
    topVersion: string,
): string {
    if (byVersion.length === 0) {
        // Rule 25: explicit no-data (version breakdown unavailable) instead of silent omission.
        return EmptyState({
            title: 'No version breakdown data available',
            description:
                'Version breakdown requires AI acceptance results grouped by prompt version. No records were found.',
            action: 'Run AI effectiveness tracking across prompt versions to populate the breakdown.',
            icon: icon('bar-chart', 16),
        });
    }

    // Find best and worst versions for highlighting
    const sorted = [...byVersion].sort((a, b) => b.acceptanceRate - a.acceptanceRate);
    const bestVersion = sorted[0]?.version;
    const worstVersion = sorted[sorted.length - 1]?.version;

    const columns: TableColumn[] = [
        { key: 'version', label: 'Prompt Version' },
        { key: 'count', label: 'Records', align: 'right' },
        { key: 'acceptanceRate', label: 'Acceptance Rate', align: 'right' },
        { key: 'quality', label: 'Quality' },
    ];

    const rows: TableRow[] = byVersion.map((v) => {
        // Determine quality badge
        let qualityBadge: string;
        if (v.version === bestVersion && v.acceptanceRate >= 80) {
            qualityBadge = `<span data-component="badge" data-variant="pass">Best</span>`;
        } else if (v.version === worstVersion && v.acceptanceRate < 50) {
            qualityBadge = `<span data-component="badge" data-variant="fail">Needs Work</span>`;
        } else if (v.version === topVersion) {
            qualityBadge = `<span data-component="badge" data-variant="info">Most Used</span>`;
        } else {
            qualityBadge = `<span data-component="badge" data-variant="default">—</span>`;
        }

        return {
            key: v.version,
            cells: {
                version: sanitizeHtml(v.version),
                count: String(v.count),
                acceptanceRate: v.acceptanceRate + '%',
                quality: qualityBadge,
            },
        };
    });

    return Section({
        dataSection: 'version-breakdown',
        title: 'Version Breakdown',
        children: DataTable({
            columns,
            rows,
            caption: 'AI generation results grouped by prompt version',
        }),
    });
}

function buildTrendChart(trend: Array<{ date: string; acceptanceRate: number; generated: number }>): string {
    // Rule 25: explicit no-data (trend unavailable) instead of silent omission.
    if (trend.length === 0) {
        return EmptyState({
            title: 'No trend data available',
            description: 'The acceptance trend requires dated AI run results. No trend points were found.',
            action: 'Run the AI effectiveness pipeline on multiple dates so the trend can be plotted.',
            icon: icon('trending-up', 16),
        });
    }

    // Convert trend data to TrendChart points
    const points = trend.map((t) => ({
        passRate: t.acceptanceRate,
        label: t.date,
    }));

    // Calculate trend summary
    const firstRate = trend[0]?.acceptanceRate ?? 0;
    const lastRate = trend[trend.length - 1]?.acceptanceRate ?? 0;
    let trendDirection: string;
    if (lastRate > firstRate) {
        trendDirection = 'improving';
    } else if (lastRate < firstRate) {
        trendDirection = 'declining';
    } else {
        trendDirection = 'stable';
    }
    const trendDelta = lastRate - firstRate;

    // Build trend table for detailed view
    const columns: TableColumn[] = [
        { key: 'date', label: 'Date' },
        { key: 'generated', label: 'Generated', align: 'right' },
        { key: 'acceptanceRate', label: 'Acceptance Rate', align: 'right' },
    ];

    const rows: TableRow[] = trend.map((t) => ({
        key: t.date,
        cells: {
            date: sanitizeHtml(t.date),
            generated: String(t.generated),
            acceptanceRate: t.acceptanceRate + '%',
        },
    }));

    return Section({
        dataSection: 'trend',
        title: 'Daily Trend',
        children:
            `<div data-part="trend-summary">
            <p>Trend: <strong>${trendDirection}</strong> (${trendDelta >= 0 ? '+' : ''}${trendDelta}% over ${trend.length} days)</p>
        </div>` +
            TrendChart({
                points,
                refLine: 80,
                refLabel: '80% target',
                role: 'img',
                ariaLabel: `Acceptance rate trend: ${trendDirection} from ${firstRate}% to ${lastRate}%`,
            }) +
            DataTable({
                columns,
                rows,
                caption: 'Daily acceptance rate trend',
            }),
    });
}

function buildActions(result: AiMetricsResult): string {
    const actions: Array<{ severity: 'error' | 'warn' | 'info'; text: string }> = [];

    // Action 1: Low acceptance rate
    if (result.acceptanceRate < 50) {
        actions.push({
            severity: 'error',
            text: `Acceptance rate is ${result.acceptanceRate}% — critically low. Review prompt templates and test generation parameters immediately.`,
        });
    } else if (result.acceptanceRate < 80) {
        actions.push({
            severity: 'warn',
            text: `Acceptance rate is ${result.acceptanceRate}% — below target. Consider adjusting prompt templates for better results.`,
        });
    }

    // Action 2: Best version identification
    if (result.byVersion.length > 1) {
        const sorted = [...result.byVersion].sort((a, b) => b.acceptanceRate - a.acceptanceRate);
        const best = sorted[0];
        if (best && best.acceptanceRate > 80) {
            actions.push({
                severity: 'info',
                text: `Prompt "${sanitizeHtml(best.version)}" has ${best.acceptanceRate}% acceptance — consider reusing for new tests.`,
            });
        }
    }

    // Action 3: Sample size warning
    if (result.totalRecords < 30) {
        actions.push({
            severity: 'warn',
            text: `Only ${result.totalRecords} records — results may not be statistically significant. Increase sample size for reliable insights.`,
        });
    }

    // Action 4: High deletion rate
    if (result.totalDeleted > 10) {
        actions.push({
            severity: 'warn',
            text: `${result.totalDeleted} tests were deleted — review deletion reasons to identify systematic issues.`,
        });
    }

    // Action 5: Stable/improving trend
    if (result.trend.length >= 2) {
        const firstRate = result.trend[0]?.acceptanceRate ?? 0;
        const lastRate = result.trend[result.trend.length - 1]?.acceptanceRate ?? 0;
        if (lastRate > firstRate + 5) {
            actions.push({
                severity: 'info',
                text: `Acceptance rate improved by ${lastRate - firstRate}% over the period — current approach is working.`,
            });
        }
    }

    // Default action if no issues found
    if (actions.length === 0) {
        actions.push({
            severity: 'info',
            text: 'AI effectiveness is within acceptable ranges. Continue monitoring acceptance rates and prompt version performance.',
        });
    }

    return Section({
        dataSection: 'actions',
        title: 'Recommended Actions',
        children: RecommendedActions({ actions }),
    });
}
