/**
 * AI Generation Effectiveness Dashboard — aggregates AI feedback data and
 * generates a visual HTML report with acceptance rates, version breakdown, and daily trend.
 *
 * @module ai-effectiveness
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { rootLogger } from '../logger.js';

interface AiFeedbackRecord {
    timestamp: string;
    promptVersion: string;
    testTitle: string;
    accepted: boolean;
    modificationReason?: string;
    user?: string;
}

interface AiFeedbackStore {
    records: AiFeedbackRecord[];
}

export interface AiEffectivenessResult {
    acceptanceRate: number;
    totalRecords: number;
    totalGenerated: number;
    totalModified: number;
    totalDeleted: number;
    topPromptVersion: string;
    byVersion: Array<{ version: string; count: number; acceptanceRate: number }>;
    trend: Array<{ date: string; acceptanceRate: number; generated: number }>;
    timestamp: string;
}

export function computeAiEffectiveness(store: AiFeedbackStore | null | undefined): AiEffectivenessResult {
    if (!store || store.records.length === 0) {
        return {
            acceptanceRate: 0,
            totalRecords: 0,
            totalGenerated: 0,
            totalModified: 0,
            totalDeleted: 0,
            topPromptVersion: '',
            byVersion: [],
            trend: [],
            timestamp: new Date().toISOString(),
        };
    }

    const totalRecords = store.records.length;
    const accepted = store.records.filter((r) => r.accepted).length;
    const acceptanceRate = Math.round((accepted / totalRecords) * 100);
    const totalGenerated = totalRecords;
    const totalModified = store.records.filter((r) => !r.accepted && r.modificationReason !== 'deleted').length;
    const totalDeleted = store.records.filter((r) => !r.accepted && r.modificationReason === 'deleted').length;

    const versionMap = new Map<string, { count: number; accepted: number }>();
    for (const r of store.records) {
        const entry = versionMap.get(r.promptVersion) ?? { count: 0, accepted: 0 };
        entry.count++;
        if (r.accepted) entry.accepted++;
        versionMap.set(r.promptVersion, entry);
    }

    let topPromptVersion = '';
    let maxCount = 0;
    const byVersion: Array<{ version: string; count: number; acceptanceRate: number }> = [];
    for (const [version, data] of versionMap) {
        const rate = Math.round((data.accepted / data.count) * 100);
        byVersion.push({ version, count: data.count, acceptanceRate: rate });
        if (data.count > maxCount) {
            maxCount = data.count;
            topPromptVersion = version;
        }
    }

    const dateMap = new Map<string, { generated: number; accepted: number }>();
    for (const r of store.records) {
        const date = r.timestamp.slice(0, 10);
        const entry = dateMap.get(date) ?? { generated: 0, accepted: 0 };
        entry.generated++;
        if (r.accepted) entry.accepted++;
        dateMap.set(date, entry);
    }

    const trend: Array<{ date: string; acceptanceRate: number; generated: number }> = [];
    for (const [date, data] of dateMap) {
        const rate = Math.round((data.accepted / data.generated) * 100);
        trend.push({ date, acceptanceRate: rate, generated: data.generated });
    }
    trend.sort((a, b) => a.date.localeCompare(b.date));

    return {
        acceptanceRate,
        totalRecords,
        totalGenerated,
        totalModified,
        totalDeleted,
        topPromptVersion,
        byVersion,
        trend,
        timestamp: new Date().toISOString(),
    };
}

export function generateAiEffectivenessHtml(result: AiEffectivenessResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            return buildErrorPage('Error generating dashboard', 'Invalid or missing AI effectiveness data');
        }
        const pageTitle = title || 'AI Effectiveness Dashboard';
        let bodyContent = `<h1>${sanitizeHtml(pageTitle)}</h1>`;

        if (result.totalRecords === 0) {
            bodyContent += '<p>No AI generation data available</p>';
        } else {
            bodyContent += buildMetricLarge(result.acceptanceRate, result.totalRecords);
            bodyContent += buildVersionTable(result.byVersion);
            bodyContent += buildTrendTable(result.trend);
        }

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: `Generated by QA Tools — ${pageTitle}`,
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error('Failed to generate AI effectiveness dashboard: ' + msg);
        return buildErrorPage(
            'Error generating dashboard',
            'An error occurred while generating the AI effectiveness dashboard. Check the logs for details and ensure your AI feedback data is valid.',
        );
    }
}

function buildMetricLarge(rate: number, total: number): string {
    return `<div style="text-align:center;padding:2rem 0">
        <div style="font-size:3rem;font-weight:700;color:var(--color-text-primary)">${rate}%</div>
        <div style="font-size:1rem;color:var(--color-text-secondary)">Acceptance Rate</div>
        <div style="font-size:0.875rem;color:var(--color-text-secondary)">${total} total records</div>
    </div>`;
}

function buildVersionTable(byVersion: Array<{ version: string; count: number; acceptanceRate: number }>): string {
    let html = '<h2>By Prompt Version</h2>';
    html +=
        '<div style="overflow-x:auto;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.1)"><table style="width:100%;border-collapse:collapse;background:var(--color-surface-card);font-size:0.875rem;color:var(--color-text-primary)">';
    html += '<thead style="background:var(--color-surface-elevated)"><tr>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Version</th>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:right">Records</th>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:right">Acceptance Rate</th>';
    html += '</tr></thead><tbody>';
    for (const v of byVersion) {
        html += '<tr style="border-bottom:1px solid var(--color-border-subtle)">';
        html += `<td style="padding:8px 12px">${sanitizeHtml(v.version)}</td>`;
        html += `<td style="padding:8px 12px;text-align:right">${v.count}</td>`;
        html += `<td style="padding:8px 12px;text-align:right">${v.acceptanceRate}%</td>`;
        html += '</tr>';
    }
    html += '</tbody></table></div>';
    return html;
}

function buildTrendTable(trend: Array<{ date: string; acceptanceRate: number; generated: number }>): string {
    let html = '<h2>Daily Trend</h2>';
    html +=
        '<div style="overflow-x:auto;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.1)"><table style="width:100%;border-collapse:collapse;background:var(--color-surface-card);font-size:0.875rem;color:var(--color-text-primary)">';
    html += '<thead style="background:var(--color-surface-elevated)"><tr>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Date</th>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:right">Generated</th>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:right">Acceptance Rate</th>';
    html += '</tr></thead><tbody>';
    for (const t of trend) {
        html += '<tr style="border-bottom:1px solid var(--color-border-subtle)">';
        html += `<td style="padding:8px 12px">${sanitizeHtml(t.date)}</td>`;
        html += `<td style="padding:8px 12px;text-align:right">${t.generated}</td>`;
        html += `<td style="padding:8px 12px;text-align:right">${t.acceptanceRate}%</td>`;
        html += '</tr>';
    }
    html += '</tbody></table></div>';
    return html;
}

import type { AiGenerationRecord } from '../types/llm.js';

/** Converts AiGenerationRecord[] (from DataHub) to AiFeedbackRecord[] for computeAiEffectiveness. */
export function convertGenerationRecordsToFeedback(records: AiGenerationRecord[] | null | undefined): {
    records: Array<{
        timestamp: string;
        promptVersion: string;
        testTitle: string;
        accepted: boolean;
        modificationReason?: string;
    }>;
} {
    if (!records || records.length === 0) {
        return { records: [] };
    }
    const feedbackRecords: Array<{
        timestamp: string;
        promptVersion: string;
        testTitle: string;
        accepted: boolean;
        modificationReason?: string;
    }> = [];
    for (const record of records) {
        if (!record.feedback) continue;
        for (const fb of record.feedback) {
            const accepted = fb.action === 'kept' || fb.action === 'modified';
            const entry: {
                timestamp: string;
                promptVersion: string;
                testTitle: string;
                accepted: boolean;
                modificationReason?: string;
            } = {
                timestamp: fb.recordedAt,
                promptVersion: record.promptVersion,
                testTitle: fb.testKey,
                accepted,
            };
            if (fb.reason) entry.modificationReason = fb.reason;
            feedbackRecords.push(entry);
        }
    }
    return { records: feedbackRecords };
}
