/**
 * AI Effectiveness Dashboard — HTML rendering layer.
 *
 * Receives computed AiEffectivenessResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module ai-effectiveness-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { rootLogger } from '../logger.js';
import { MetricCard, MetricGrid, DataTable, Section, EmptyState, RecommendedActions } from '../primitives/index.js';
import type { TableColumn, TableRow } from '../primitives/index.js';
import type { AiEffectivenessResult } from './ai-effectiveness.js';

export function generateAiEffectivenessHtml(result: AiEffectivenessResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            rootLogger.error(
                'AI effectiveness result is null or undefined. Verify that AI feedback data is being collected and passed correctly.',
            );
            return buildErrorPage('Error generating dashboard', 'Invalid or missing AI effectiveness data');
        }
        const pageTitle = title || 'AI Effectiveness Dashboard';

        if (result.totalRecords === 0) {
            return buildHtmlPage({
                title: pageTitle,
                styles: buildCss(),
                theme: 'system',
                bodyContent: Container(
                    pageTitle,
                    EmptyState({
                        title: 'No AI generation data available',
                        description:
                            'No AI-generated test records were found. This dashboard requires test data produced by the AI generation pipeline.',
                        action: 'Run the AI generation pipeline to produce test data, then regenerate this report.',
                    }),
                ),
                footer: `Generated by QA Tools — ${pageTitle}`,
            });
        }

        const bodyContent = Container(
            pageTitle,
            buildMetricSummary(result.acceptanceRate, result.totalRecords) +
                buildVersionTable(result.byVersion) +
                buildTrendTable(result.trend) +
                buildActions(),
        );

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: `Generated by QA Tools — ${pageTitle}`,
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error(
            'Failed to generate AI effectiveness dashboard: ' +
                msg +
                '. Verify that AI feedback data contains valid acceptanceRate, byVersion, and trend fields.',
        );
        return buildErrorPage(
            'Error generating dashboard',
            'An error occurred while generating the AI effectiveness dashboard. Check the logs for details and ensure your AI feedback data is valid.',
        );
    }
}

function Container(pageTitle: string, children: string): string {
    return `<div data-component="container" data-dashboard="ai-effectiveness">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        ${children}
    </div>`;
}

function buildMetricSummary(rate: number, total: number): string {
    let severity: 'success' | 'warn' | 'error';
    if (rate >= 80) {
        severity = 'success';
    } else if (rate >= 50) {
        severity = 'warn';
    } else {
        severity = 'error';
    }

    return Section({
        title: 'Acceptance Rate',
        children: MetricGrid({
            children: MetricCard({
                label: 'Acceptance Rate',
                value: rate + '%',
                severity,
                trend: total + ' total records',
            }),
        }),
    });
}

function buildVersionTable(byVersion: Array<{ version: string; count: number; acceptanceRate: number }>): string {
    if (byVersion.length === 0) return '';

    const columns: TableColumn[] = [
        { key: 'version', label: 'Prompt Version' },
        { key: 'count', label: 'Records', align: 'right' },
        { key: 'acceptanceRate', label: 'Acceptance Rate', align: 'right' },
    ];

    const rows: TableRow[] = byVersion.map((v) => ({
        key: v.version,
        cells: {
            version: sanitizeHtml(v.version),
            count: String(v.count),
            acceptanceRate: v.acceptanceRate + '%',
        },
    }));

    return Section({
        dataSection: 'version-breakdown',
        title: 'By Prompt Version',
        children: DataTable({
            columns,
            rows,
            caption: 'AI generation results grouped by prompt version',
        }),
    });
}

function buildTrendTable(trend: Array<{ date: string; acceptanceRate: number; generated: number }>): string {
    if (trend.length === 0) return '';

    const columns: TableColumn[] = [
        { key: 'date', label: 'Date' },
        { key: 'generated', label: 'Generated', align: 'right' },
        { key: 'acceptanceRate', label: 'Acceptance Rate', align: 'right' },
    ];

    const rows: TableRow[] = trend.map((t) => ({
        key: t.date,
        cells: {
            date: sanitizeHtml(t.date),
            generated: String(t.generated),
            acceptanceRate: t.acceptanceRate + '%',
        },
    }));

    return Section({
        dataSection: 'trend',
        title: 'Daily Trend',
        children: DataTable({
            columns,
            rows,
            caption: 'Daily acceptance rate trend',
        }),
    });
}

function buildActions(): string {
    return Section({
        dataSection: 'actions',
        children: RecommendedActions({
            actions: [
                { severity: 'info', text: 'Review acceptance rates below 50% — consider adjusting prompt templates.' },
                {
                    severity: 'info',
                    text: 'Compare version breakdown to identify the most effective prompt versions for reuse.',
                },
            ],
        }),
    });
}
