/**
 * AI Effectiveness Dashboard — HTML rendering layer.
 *
 * Receives computed AiEffectivenessResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module ai-effectiveness-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { rootLogger } from '../logger.js';
import type { AiEffectivenessResult } from './ai-effectiveness.js';

export function generateAiEffectivenessHtml(result: AiEffectivenessResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            return buildErrorPage('Error generating dashboard', 'Invalid or missing AI effectiveness data');
        }
        const pageTitle = title || 'AI Effectiveness Dashboard';
        let bodyContent = `<h1>${sanitizeHtml(pageTitle)}</h1>`;

        if (result.totalRecords === 0) {
            bodyContent += '<p>No AI generation data available</p>';
        } else {
            bodyContent += buildMetricLarge(result.acceptanceRate, result.totalRecords);
            bodyContent += buildVersionTable(result.byVersion);
            bodyContent += buildTrendTable(result.trend);
        }

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: `Generated by QA Tools — ${pageTitle}`,
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error('Failed to generate AI effectiveness dashboard: ' + msg);
        return buildErrorPage(
            'Error generating dashboard',
            'An error occurred while generating the AI effectiveness dashboard. Check the logs for details and ensure your AI feedback data is valid.',
        );
    }
}

function buildMetricLarge(rate: number, total: number): string {
    return `<div style="text-align:center;padding:2rem 0">
        <div style="font-size:3rem;font-weight:700;color:var(--color-text-primary)">${rate}%</div>
        <div style="font-size:1rem;color:var(--color-text-secondary)">Acceptance Rate</div>
        <div style="font-size:0.875rem;color:var(--color-text-secondary)">${total} total records</div>
    </div>`;
}

function buildVersionTable(byVersion: Array<{ version: string; count: number; acceptanceRate: number }>): string {
    let html = '<h2>By Prompt Version</h2>';
    html +=
        '<div style="overflow-x:auto;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.1)"><table style="width:100%;border-collapse:collapse;background:var(--color-surface-card);font-size:0.875rem;color:var(--color-text-primary)">';
    html += '<thead style="background:var(--color-surface-elevated)"><tr>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Version</th>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:right">Records</th>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:right">Acceptance Rate</th>';
    html += '</tr></thead><tbody>';
    for (const v of byVersion) {
        html += '<tr style="border-bottom:1px solid var(--color-border-subtle)">';
        html += `<td style="padding:8px 12px">${sanitizeHtml(v.version)}</td>`;
        html += `<td style="padding:8px 12px;text-align:right">${v.count}</td>`;
        html += `<td style="padding:8px 12px;text-align:right">${v.acceptanceRate}%</td>`;
        html += '</tr>';
    }
    html += '</tbody></table></div>';
    return html;
}

function buildTrendTable(trend: Array<{ date: string; acceptanceRate: number; generated: number }>): string {
    let html = '<h2>Daily Trend</h2>';
    html +=
        '<div style="overflow-x:auto;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.1)"><table style="width:100%;border-collapse:collapse;background:var(--color-surface-card);font-size:0.875rem;color:var(--color-text-primary)">';
    html += '<thead style="background:var(--color-surface-elevated)"><tr>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Date</th>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:right">Generated</th>';
    html +=
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:right">Acceptance Rate</th>';
    html += '</tr></thead><tbody>';
    for (const t of trend) {
        html += '<tr style="border-bottom:1px solid var(--color-border-subtle)">';
        html += `<td style="padding:8px 12px">${sanitizeHtml(t.date)}</td>`;
        html += `<td style="padding:8px 12px;text-align:right">${t.generated}</td>`;
        html += `<td style="padding:8px 12px;text-align:right">${t.acceptanceRate}%</td>`;
        html += '</tr>';
    }
    html += '</tbody></table></div>';
    return html;
}
