/**
 * Backlog Health Dashboard — HTML rendering layer.
 *
 * Receives computed BacklogHealthResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module backlog-health-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { rootLogger } from '../logger.js';
import { Card, MetricCard, MetricGrid, Badge, DataTable, Section, EmptyState } from '../primitives/index.js';
import type { TableColumn, TableRow } from '../primitives/index.js';
import type { BacklogHealthResult, BacklogHealthIssue } from './backlog-health.js';

const SUMMARY_TRUNCATE_LENGTH = 80;
const SCORE_THRESHOLD_SUCCESS = 80;
const SCORE_THRESHOLD_WARN = 50;

export function generateBacklogHealthHtml(result: BacklogHealthResult, title?: string): string {
    try {
        const pageTitle = title || 'Backlog Health Dashboard';

        const bodyContent = wrapContainer(
            pageTitle,
            buildMetricSummary(result) +
                (result.noData
                    ? EmptyState({
                          title: 'No backlog data available',
                          description:
                              'Backlog health metrics require issue data from your project management tool. No issues were found to analyze.',
                          action: 'Configure Jira/issue tracker integration and run the backlog analysis pipeline to generate data.',
                      })
                    : '') +
                buildIssueCards(result) +
                buildDensitySection(result),
        );

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Backlog Health Dashboard',
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error(
            'Failed to generate backlog health dashboard: ' +
                msg +
                '. Verify that backlog data contains valid score, unassignedIssues, staleIssues, bugsWithoutTests, and densityByEpic fields.',
        );
        return buildErrorPage('Error generating dashboard', 'Error generating backlog health dashboard');
    }
}

function wrapContainer(pageTitle: string, children: string): string {
    return `<div data-component="container" data-dashboard="backlog-health">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        ${children}
    </div>`;
}

function buildMetricSummary(result: BacklogHealthResult): string {
    let scoreSeverity: 'success' | 'warn' | 'error';
    if (result.score >= SCORE_THRESHOLD_SUCCESS) {
        scoreSeverity = 'success';
    } else if (result.score >= SCORE_THRESHOLD_WARN) {
        scoreSeverity = 'warn';
    } else {
        scoreSeverity = 'error';
    }

    return Section({
        dataSection: 'summary',
        children: MetricGrid({
            children:
                MetricCard({
                    label: 'Backlog Score',
                    value: result.noData ? 'N/A' : String(result.score) + '%',
                    severity: result.noData ? 'warn' : scoreSeverity,
                }) +
                MetricCard({
                    label: 'Unassigned',
                    value: String(result.unassignedIssues.length),
                    severity: result.unassignedIssues.length > 0 ? 'warn' : 'success',
                }) +
                MetricCard({
                    label: 'Stale Issues',
                    value: String(result.staleIssues.length),
                    severity: result.staleIssues.length > 0 ? 'warn' : 'success',
                }) +
                MetricCard({
                    label: 'Bugs Without Tests',
                    value: String(result.bugsWithoutTests.length),
                    severity: result.bugsWithoutTests.length > 0 ? 'error' : 'success',
                }),
        }),
    });
}

function buildIssueCards(result: BacklogHealthResult): string {
    let html = '';

    if (result.unassignedIssues.length > 0) {
        html += Card({
            title: 'Unassigned Issues (' + result.unassignedIssues.length + ')',
            variant: 'bordered',
            severity: 'warn',
            children: buildIssueListCapped(result.unassignedIssues, result.displayLimit),
        });
    }

    if (result.staleIssues.length > 0) {
        html += Card({
            title: 'Stale Issues (' + result.staleIssues.length + ')',
            variant: 'bordered',
            severity: 'warn',
            children: buildIssueListCapped(result.staleIssues, result.displayLimit),
        });
    }

    if (result.bugsWithoutTests.length > 0) {
        html += Card({
            title: 'Bugs Without Tests (' + result.bugsWithoutTests.length + ')',
            variant: 'bordered',
            severity: 'error',
            children: buildIssueListCapped(result.bugsWithoutTests, result.displayLimit),
        });
    }

    return html;
}

function buildIssueListCapped(issues: BacklogHealthIssue[], limit?: number): string {
    const hasLimit = typeof limit === 'number' && limit >= 0;
    const visible = hasLimit ? issues.slice(0, limit) : issues;
    const items = visible
        .map(
            (issue) =>
                `<li data-component="issue-item">
            <span data-part="key">${sanitizeHtml(issue.key)}</span>
            <span data-part="summary">${sanitizeHtml(issue.summary.slice(0, SUMMARY_TRUNCATE_LENGTH))}</span>
            ${Badge({ variant: issue.type === 'Bug' ? 'fail' : 'warn', children: issue.type })}
        </li>`,
        )
        .join('');

    const overflow =
        hasLimit && issues.length > limit
            ? `<li data-part="overflow">Showing first ${String(limit)} of ${String(issues.length)} issues.</li>`
            : '';

    return `<ul data-component="issue-list">${items}${overflow}</ul>`;
}

function buildDensitySection(result: BacklogHealthResult): string {
    if (result.densityByEpic.length === 0) return '';

    const columns: TableColumn[] = [
        { key: 'epic', label: 'Epic' },
        { key: 'bugs', label: 'Bugs', align: 'right' },
        { key: 'tests', label: 'Tests', align: 'right' },
        { key: 'ratio', label: 'Ratio', align: 'right' },
    ];

    const rows: TableRow[] = result.densityByEpic.map((d) => ({
        key: d.epic,
        cells: {
            epic: sanitizeHtml(d.epic),
            bugs: String(d.bugCount),
            tests: String(d.testCount),
            ratio: d.bugCount > 0 ? (d.testCount / d.bugCount).toFixed(1) : '\u2014',
        },
    }));

    return Section({
        dataSection: 'density',
        title: 'Density by Epic',
        children: DataTable({
            columns,
            rows,
            caption: 'Bug density by epic — tests per bug ratio',
        }),
    });
}
