/**
 * Backlog Health Dashboard — HTML rendering layer.
 *
 * Receives computed BacklogHealthResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module backlog-health-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { rootLogger } from '../logger.js';
import {
    Card,
    MetricCard,
    MetricGrid,
    Badge,
    DataTable,
    Section,
    EmptyState,
    RecommendedActions,
} from '../primitives/index.js';
import type { TableColumn, TableRow } from '../primitives/index.js';
import type { BacklogHealthResult, BacklogHealthIssue } from './backlog-health.js';

const SUMMARY_TRUNCATE_LENGTH = 80;
const SCORE_THRESHOLD_SUCCESS = 80;
const SCORE_THRESHOLD_WARN = 50;

export function generateBacklogHealthHtml(result: BacklogHealthResult | null | undefined, title?: string): string {
    try {
        const pageTitle = title || 'Backlog Health Dashboard';

        if (!result) {
            rootLogger.error('generateBacklogHealthHtml: backlog health result is missing.');
            return buildErrorPage('Error generating dashboard', 'Backlog health data is unavailable.');
        }

        const bodyContent = wrapContainer(
            pageTitle,
            buildMetricSummary(result) +
                (result.noData
                    ? EmptyState({
                          title: 'No backlog data available',
                          description:
                              'Backlog health metrics require issue data from your project management tool. No issues were found to analyze.',
                          action: 'Configure Jira/issue tracker integration and run the backlog analysis pipeline to generate data.',
                      })
                    : '') +
                buildIssueCards(result) +
                buildDensitySection(result) +
                buildRecommendedActions(result),
            result.timestamp,
        );

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Backlog Health Dashboard',
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error(
            'Failed to generate backlog health dashboard: ' +
                msg +
                '. Verify that backlog data contains valid score, unassignedIssues, staleIssues, bugsWithoutTests, and densityByEpic fields.',
        );
        return buildErrorPage('Error generating dashboard', 'Error generating backlog health dashboard');
    }
}

function wrapContainer(pageTitle: string, children: string, timestamp: string): string {
    return `<div data-component="container" data-dashboard="backlog-health">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        <div data-part="timestamp">${sanitizeHtml(timestamp)}</div>
        ${children}
    </div>`;
}

function buildMetricSummary(result: BacklogHealthResult): string {
    let scoreSeverity: 'success' | 'warn' | 'error';
    if (result.score >= SCORE_THRESHOLD_SUCCESS) {
        scoreSeverity = 'success';
    } else if (result.score >= SCORE_THRESHOLD_WARN) {
        scoreSeverity = 'warn';
    } else {
        scoreSeverity = 'error';
    }

    // Calculate total issues for context
    const totalIssues = result.totalIssues || 0;
    const unassignedRate = totalIssues > 0 ? Math.round((result.unassignedIssues.length / totalIssues) * 100) : 0;
    const staleRate = totalIssues > 0 ? Math.round((result.staleIssues.length / totalIssues) * 100) : 0;

    return Section({
        dataSection: 'summary',
        title: 'Summary',
        children: MetricGrid({
            children:
                MetricCard({
                    label: 'Backlog Score',
                    value: result.noData ? 'N/A' : String(result.score) + '%',
                    severity: result.noData ? 'warn' : scoreSeverity,
                    trend: totalIssues > 0 ? `${totalIssues} total issues` : '',
                    target: `target: >=${SCORE_THRESHOLD_SUCCESS}%`,
                }) +
                MetricCard({
                    label: 'Unassigned',
                    value: String(result.unassignedIssues.length),
                    severity: result.unassignedIssues.length > 0 ? 'warn' : 'success',
                    trend: totalIssues > 0 ? `${unassignedRate}% of total` : '',
                    target: 'target: 0',
                }) +
                MetricCard({
                    label: 'Stale Issues',
                    value: String(result.staleIssues.length),
                    severity: result.staleIssues.length > 0 ? 'warn' : 'success',
                    trend: totalIssues > 0 ? `${staleRate}% of total` : '',
                    target: 'target: 0',
                }) +
                MetricCard({
                    label: 'Bugs w/o Tests',
                    value: String(result.bugsWithoutTests.length),
                    severity: result.bugsWithoutTests.length > 0 ? 'error' : 'success',
                    target: 'target: 0',
                }),
        }),
    });
}

function buildIssueCards(result: BacklogHealthResult): string {
    let html = '';

    if (result.unassignedIssues.length > 0) {
        html += Card({
            title: 'Unassigned Issues (' + result.unassignedIssues.length + ')',
            variant: 'bordered',
            severity: 'warn',
            children: buildIssueListCapped(result.unassignedIssues, result.displayLimit),
        });
    }

    if (result.staleIssues.length > 0) {
        // Calculate how stale the issues are
        const now = new Date();
        const staleAges = result.staleIssues
            .map((issue) => {
                const updated = new Date(issue.updated);
                const daysSinceUpdate = Math.floor((now.getTime() - updated.getTime()) / (1000 * 60 * 60 * 24));
                return daysSinceUpdate;
            })
            .filter((days) => days >= 0);
        const avgStaleDays =
            staleAges.length > 0 ? Math.round(staleAges.reduce((a, b) => a + b, 0) / staleAges.length) : 0;

        html += Card({
            title: 'Stale Issues (' + result.staleIssues.length + ')',
            variant: 'bordered',
            severity: 'warn',
            children:
                `<p data-part="stale-description">Average age: ${avgStaleDays} days without update</p>` +
                buildIssueListCapped(result.staleIssues, result.displayLimit),
        });
    }

    if (result.bugsWithoutTests.length > 0) {
        html += Card({
            title: 'Bugs w/o Tests (' + result.bugsWithoutTests.length + ')',
            variant: 'bordered',
            severity: 'error',
            children: buildIssueListCapped(result.bugsWithoutTests, result.displayLimit),
        });
    }

    return html;
}

function buildIssueListCapped(issues: BacklogHealthIssue[], limit?: number): string {
    const hasLimit = typeof limit === 'number' && limit >= 0;
    const visible = hasLimit ? issues.slice(0, limit) : issues;
    const items = visible
        .map(
            (issue) =>
                `<li data-component="issue-item">
            <span data-part="key">${sanitizeHtml(issue.key)}</span>
            <span data-part="summary">${sanitizeHtml(issue.summary.slice(0, SUMMARY_TRUNCATE_LENGTH))}</span>
            ${Badge({ variant: issue.type === 'Bug' ? 'fail' : 'warn', children: issue.type })}
        </li>`,
        )
        .join('');

    const overflow =
        hasLimit && issues.length > limit
            ? `<li data-part="overflow">Showing first ${String(limit)} of ${String(issues.length)} issues.</li>`
            : '';

    return `<ul data-component="issue-list">${items}${overflow}</ul>`;
}

function buildDensitySection(result: BacklogHealthResult): string {
    if (result.densityByEpic.length === 0) return '';

    // Sort by ratio (worst first) for better visibility
    const sorted = [...result.densityByEpic].sort((a, b) => {
        const ratioA = a.bugCount > 0 ? a.testCount / a.bugCount : Infinity;
        const ratioB = b.bugCount > 0 ? b.testCount / b.bugCount : Infinity;
        return ratioA - ratioB;
    });

    const columns: TableColumn[] = [
        { key: 'rank', label: '#', width: '40px', align: 'center' },
        { key: 'epic', label: 'Epic' },
        { key: 'bugs', label: 'Bugs', align: 'right' },
        { key: 'tests', label: 'Tests', align: 'right' },
        { key: 'ratio', label: 'Ratio', align: 'right' },
    ];

    const rows: TableRow[] = sorted.map((d, i) => {
        const ratio = d.bugCount > 0 ? d.testCount / d.bugCount : Infinity;
        let ratioSeverity: 'fail' | 'warn' | 'pass';
        if (ratio < 1) {
            ratioSeverity = 'fail';
        } else if (ratio < 2) {
            ratioSeverity = 'warn';
        } else {
            ratioSeverity = 'pass';
        }

        return {
            key: d.epic,
            cells: {
                rank: String(i + 1),
                epic: sanitizeHtml(d.epic),
                bugs: String(d.bugCount),
                tests: String(d.testCount),
                ratio:
                    d.bugCount > 0
                        ? Badge({ variant: ratioSeverity, children: (d.testCount / d.bugCount).toFixed(1) })
                        : '\u2014',
            },
        };
    });

    return Section({
        dataSection: 'density',
        title: 'Density by Epic (Ranked by Coverage)',
        children: DataTable({
            columns,
            rows,
            caption: 'Bug density by epic — tests per bug ratio, ranked from worst to best',
        }),
    });
}

function buildRecommendedActions(result: BacklogHealthResult): string {
    const actions: Array<{ severity: 'error' | 'warn' | 'info'; text: string }> = [];

    // Action 1: Low score
    if (result.score < SCORE_THRESHOLD_SUCCESS) {
        actions.push({
            severity: 'error',
            text: `Backlog health score is ${result.score}% (below ${SCORE_THRESHOLD_SUCCESS}% threshold). Priority: address ${result.staleIssues.length} stale and ${result.unassignedIssues.length} unassigned issues.`,
        });
    }

    // Action 2: Stale issues with context
    if (result.staleIssues.length > 0) {
        const now = new Date();
        const oldestStale = result.staleIssues.reduce((oldest, issue) => {
            if (!oldest) return issue;
            const updated = new Date(issue.updated);
            return updated < new Date(oldest.updated) ? issue : oldest;
        }, result.staleIssues[0]);

        if (oldestStale) {
            const daysSinceUpdate = Math.floor(
                (now.getTime() - new Date(oldestStale.updated).getTime()) / (1000 * 60 * 60 * 24),
            );
            actions.push({
                severity: 'warn',
                text: `${result.staleIssues.length} stale issue(s). Oldest: ${sanitizeHtml(oldestStale.key)} (${daysSinceUpdate} days old). Review and close or update outdated backlog items.`,
            });
        }
    }

    // Action 3: Unassigned issues
    if (result.unassignedIssues.length > 0) {
        const unassignedTypes = result.unassignedIssues.reduce(
            (acc, issue) => {
                acc[issue.type] = (acc[issue.type] || 0) + 1;
                return acc;
            },
            {} as Record<string, number>,
        );

        const typeBreakdown = Object.entries(unassignedTypes)
            .map(([type, count]) => `${count} ${type}`)
            .join(', ');

        actions.push({
            severity: 'warn',
            text: `${result.unassignedIssues.length} unassigned issue(s) (${typeBreakdown}). Assign owners to ensure accountability.`,
        });
    }

    // Action 4: Bugs without tests
    if (result.bugsWithoutTests.length > 0) {
        actions.push({
            severity: 'error',
            text: `${result.bugsWithoutTests.length} bug(s) have no linked tests. Add test coverage to prevent regressions.`,
        });
    }

    // Default action if no issues found
    if (actions.length === 0) {
        actions.push({
            severity: 'info',
            text: 'Backlog health is within acceptable ranges. Continue monitoring for stale or unassigned issues.',
        });
    }

    return Section({
        dataSection: 'actions',
        title: 'Recommended Actions',
        children: RecommendedActions({ actions }),
    });
}
