/**
 * Flakiness Dashboard — HTML rendering layer.
 *
 * Receives flakiness data and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module flakiness-renderer
 */

import type { FlakinessEntry, DataHub } from '../types/data-hub.js';
import { rootLogger } from '../logger.js';
import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import {
    MetricCard,
    MetricGrid,
    Badge,
    Sparkline,
    Section,
    EmptyState,
    RecommendedActions,
    THead,
    TBody,
    Tr,
    Td,
    Th,
} from '../primitives/index.js';
import type { FlakinessThresholds, FlakinessOptions } from './flakiness-dashboard.js';
import { filterHighFlakiness, validateThresholds } from './flakiness-dashboard.js';

export function generateFlakinessHtml(flaky: FlakinessEntry[], title?: string, options?: FlakinessOptions): string {
    try {
        const thresholds = validateThresholds(options?.thresholds);
        const high = filterHighFlakiness(flaky, thresholds);
        const pageTitle = title || 'Flakiness Dashboard';
        const sourceBanner = buildSourceQualityBanner(options?.dataHub);

        const bodyContent = `<div data-component="container" data-dashboard="flakiness">
            <h1>${sanitizeHtml(pageTitle)}</h1>
            ${sourceBanner}
            ${buildFlakinessSummary(high, flaky, thresholds)}
            ${buildFlakinessTable(high, thresholds)}
            ${buildActions(high, thresholds)}
        </div>`;

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Flakiness Dashboard',
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error(
            'Failed to generate flakiness dashboard. Verify that flakiness data is valid and complete, then retry. Details: ' +
                msg,
        );
        return buildErrorPage('Error generating dashboard', 'Error generating dashboard');
    }
}

function buildFlakinessSummary(
    high: FlakinessEntry[],
    flaky: FlakinessEntry[],
    thresholds: FlakinessThresholds,
): string {
    return Section({
        dataSection: 'summary',
        children: MetricGrid({
            children:
                MetricCard({
                    label: 'Total Flaky Tests',
                    value: String(high.length),
                    severity: high.length > thresholds.errorSeverityThreshold ? 'error' : 'warn',
                }) +
                MetricCard({ label: 'Threshold', value: '>' + thresholds.thresholdPct + '%' }) +
                MetricCard({ label: 'All Candidates', value: String(flaky.length) }),
        }),
    });
}

function buildFlakinessTable(high: FlakinessEntry[], thresholds: FlakinessThresholds): string {
    if (high.length === 0) {
        return Section({
            dataSection: 'flakiness-table',
            children: EmptyState({
                title: 'No flaky tests detected',
                description:
                    'No tests exceed the ' +
                    thresholds.thresholdPct +
                    '% flakiness threshold. All tests are within acceptable stability limits.',
                action: 'Flakiness is measured as non-passed runs / total runs. Continue monitoring to detect intermittent failures.',
            }),
        });
    }

    const header = THead({
        children:
            Th({ children: 'Test', scope: 'col' }) +
            Th({ children: 'Pass', scope: 'col', align: 'center' }) +
            Th({ children: 'Fail', scope: 'col', align: 'center' }) +
            Th({ children: 'Skip', scope: 'col', align: 'center' }) +
            Th({ children: 'Rate', scope: 'col', align: 'center' }) +
            Th({ children: 'Trend', scope: 'col' }),
    });

    const body = TBody({
        children: high
            .map((f) => {
                const pct = Math.round(f.rate * 100);
                const severity = pct >= thresholds.highFlakinessPct ? 'high' : 'medium';
                return Tr({
                    key: f.title,
                    children:
                        Td({ children: sanitizeHtml(f.title.slice(0, 80)) }) +
                        Td({ children: String(f.passCount), align: 'center' }) +
                        Td({ children: String(f.failCount), align: 'center' }) +
                        Td({ children: String(f.skipCount), align: 'center' }) +
                        Td({
                            children: Badge({
                                variant: severity === 'high' ? 'fail' : 'warn',
                                children: pct + '%',
                            }),
                        }) +
                        Td({
                            children: Sparkline({
                                value: pct,
                                maxValue: 100,
                                width: 100,
                                height: 8,
                            }),
                        }),
                });
            })
            .join(''),
    });

    return Section({
        dataSection: 'flakiness-table',
        title: 'Flaky Tests',
        children: `<table data-component="data-table" role="table"
            aria-label="Tests exceeding ${thresholds.thresholdPct}% flakiness threshold">
            <caption>Tests with flakiness rate above ${thresholds.thresholdPct}%</caption>
            ${header}${body}
        </table>`,
    });
}

function buildSourceQualityBanner(dataHub?: DataHub): string {
    if (!dataHub) return '';
    const parts: string[] = [];
    const provenance = dataHub.getProvenance()?.get('failureRecords');
    if (provenance && Number.isFinite(provenance.confidence)) {
        parts.push(
            `<span data-part="confidence">failure-records source confidence: ${Math.round(provenance.confidence * 100)}%</span>`,
        );
    }
    const report = dataHub.getQuality('failureRecords');
    if (report && !report.valid) {
        parts.push(
            `<span data-part="quality-warning">failure-records quality issues: ${sanitizeHtml(report.issues.join('; '))}</span>`,
        );
    }
    if (!parts.length) return '';
    return Section({
        dataSection: 'source-quality',
        children: parts.join(' '),
    });
}

function buildActions(high: FlakinessEntry[], thresholds: FlakinessThresholds): string {
    const actions: Array<{ severity: 'error' | 'warn' | 'info'; text: string }> = [];
    if (high.length > 0) {
        actions.push({
            severity: 'warn',
            text: 'Review test isolation for flaky tests — check for shared state, timing dependencies, and external service mocking.',
        });
        if (high.some((f) => Math.round(f.rate * 100) >= thresholds.highFlakinessPct)) {
            actions.push({
                severity: 'error',
                text: 'Consider quarantining tests with extreme flakiness until root cause is identified and fixed.',
            });
        }
    }
    actions.push({
        severity: 'info',
        text:
            'Flakiness threshold: >' + thresholds.thresholdPct + '%. Tests below this threshold are considered stable.',
    });

    return Section({
        dataSection: 'actions',
        children: RecommendedActions({ actions }),
    });
}
