/**
 * Flakiness Dashboard — HTML rendering layer.
 *
 * Receives flakiness data and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module flakiness-renderer
 */

import type { FlakinessEntry, DataHub } from '../types/data-hub.js';
import { rootLogger } from '../logger.js';
import { sanitizeHtml } from '../escape.js';
import { resolveGeneratedAt } from '../date-utils.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import {
    MetricCard,
    MetricGrid,
    Badge,
    Sparkline,
    Section,
    EmptyState,
    RecommendedActions,
    DataTable,
} from '../primitives/index.js';
import type { TableColumn, TableRow } from '../primitives/index.js';
import type { FlakinessThresholds, FlakinessOptions } from './flakiness-dashboard.js';
import { filterHighFlakiness, validateThresholds } from './flakiness-dashboard.js';

export function generateFlakinessHtml(flaky: FlakinessEntry[], title?: string, options?: FlakinessOptions): string {
    try {
        const thresholds = validateThresholds(options?.thresholds);
        const high = filterHighFlakiness(flaky, thresholds);
        const pageTitle = title || 'Flakiness Dashboard';
        const sourceBanner = buildSourceQualityBanner(options?.dataHub);

        // C-5 fix: use computed.flakyTestRate (domain SSOT) instead of
        // testCounts.total (cumulative — sum of all runs, wrong denominator).
        const dataHub = options?.dataHub;
        const flakyTestRateRaw = dataHub?.computed.flakyTestRate;
        const hasFlakyTestRate =
            typeof flakyTestRateRaw === 'number' && Number.isFinite(flakyTestRateRaw) && flakyTestRateRaw >= 0;
        const flakyTestRate = hasFlakyTestRate ? flakyTestRateRaw : undefined;

        const bodyContent = `<div data-component="container" data-dashboard="flakiness">
            <h1>${sanitizeHtml(pageTitle)}</h1>
            <div data-part="timestamp">${sanitizeHtml(resolveGeneratedAt(options?.generatedAt))}</div>
            ${sourceBanner}
            ${flakyTestRate === undefined ? buildNoDataBanner() : ''}
            ${buildFlakinessSummary(high, flaky, thresholds, flakyTestRate)}
            ${buildFlakinessTable(high, thresholds)}
            ${buildActions(high, thresholds, flakyTestRate)}
        </div>`;

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Flakiness Dashboard',
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error(
            'Failed to generate flakiness dashboard. Verify that flakiness data is valid and complete, then retry. Details: ' +
                msg,
        );
        return buildErrorPage('Error generating dashboard', 'Error generating dashboard');
    }
}

function buildNoDataBanner(): string {
    return Section({
        dataSection: 'no-data',
        title: 'Insufficient Data',
        children:
            'Flaky Rate indispon\u00edvel — dataHub.computed.testCounts.total ausente ou inv\u00e1lido (SSOT). Passe o DataHub (computed) ao renderer.',
    });
}

function buildFlakinessSummary(
    high: FlakinessEntry[],
    flaky: FlakinessEntry[],
    thresholds: FlakinessThresholds,
    flakyTestRate: number | undefined,
): string {
    const hasRate = flakyTestRate !== undefined;
    const rateDisplay = hasRate ? `${Math.round(flakyTestRate)}%` : 'N/A';

    return Section({
        dataSection: 'summary',
        title: 'Summary',
        children: MetricGrid({
            children:
                // 1. Flaky Tests
                MetricCard({
                    label: 'Flaky Tests',
                    value: String(high.length),
                    severity: high.length > thresholds.errorSeverityThreshold ? 'error' : 'warn',
                    trend: hasRate ? `flaky rate: ${rateDisplay}` : '',
                    target: `target: <${thresholds.errorSeverityThreshold}`,
                }) +
                // 2. Flaky Rate (SSOT from computed.flakyTestRate)
                MetricCard({
                    label: 'Flaky Rate',
                    value: rateDisplay,
                    severity: hasRate && flakyTestRate > 5 ? 'warn' : 'default',
                    target: 'target: <5%',
                }) +
                // 3. High Flakiness
                MetricCard({
                    label: 'High Flakiness',
                    value: String(flaky.length),
                    severity: flaky.length > high.length * 2 ? 'warn' : 'default',
                    trend: `${high.length} high severity`,
                }) +
                // 4. Threshold
                MetricCard({
                    label: 'Threshold',
                    value: `>${thresholds.thresholdPct}%`,
                    severity: 'default',
                    target: `target: <${thresholds.thresholdPct}%`,
                }),
        }),
    });
}

function buildFlakinessTable(high: FlakinessEntry[], thresholds: FlakinessThresholds): string {
    if (high.length === 0) {
        return Section({
            dataSection: 'flakiness-table',
            children: EmptyState({
                title: 'No flaky tests detected',
                description:
                    'No tests exceed the ' +
                    thresholds.thresholdPct +
                    '% flakiness threshold. All tests are within acceptable stability limits.',
                action: 'Flakiness is measured as non-passed runs / total runs. Continue monitoring to detect intermittent failures.',
            }),
        });
    }

    // Sort by flakiness rate (highest first) for better prioritization
    const sorted = [...high].sort((a, b) => b.rate - a.rate);

    const columns: TableColumn[] = [
        { key: 'test', label: 'Test', width: '30%' },
        { key: 'rate', label: 'Flakiness (%)', align: 'center' },
        { key: 'severity', label: 'Severity Badge' },
        { key: 'sparkline', label: 'Sparkline' },
        { key: 'runs', label: 'Runs', align: 'center' },
    ];

    const rows: TableRow[] = sorted.map((f) => {
        const pct = Math.round(f.rate * 100);
        const severity = pct >= thresholds.highFlakinessPct ? 'high' : 'medium';
        const severityVariant = severity === 'high' ? 'fail' : 'warn';

        return {
            key: f.title,
            cells: {
                test: sanitizeHtml(f.title.slice(0, 80)),
                rate: Badge({
                    variant: severityVariant,
                    children: pct + '%',
                }),
                severity: Badge({
                    variant: severityVariant,
                    children: severity === 'high' ? 'High' : 'Medium',
                }),
                sparkline: Sparkline({
                    value: pct,
                    maxValue: 100,
                    width: 100,
                    height: 8,
                }),
                runs: String(f.totalRuns),
            },
        };
    });

    return Section({
        dataSection: 'flakiness-table',
        title: 'Flaky Tests Table',
        children: DataTable({
            columns,
            rows,
            caption: `Tests with flakiness rate above ${thresholds.thresholdPct}% — sorted by severity`,
        }),
    });
}

function buildSourceQualityBanner(dataHub?: DataHub): string {
    const parts: string[] = [];
    if (dataHub) {
        const provenance = dataHub.getProvenance()?.get('failureRecords');
        if (provenance && Number.isFinite(provenance.confidence)) {
            parts.push(
                `<span data-part="confidence">failure-records source confidence: ${Math.round(provenance.confidence * 100)}%</span>`,
            );
        }
        const report = dataHub.getQuality('failureRecords');
        if (report && !report.valid) {
            parts.push(
                `<span data-part="quality-warning">failure-records quality issues: ${sanitizeHtml(report.issues.join('; '))}</span>`,
            );
        }
    }
    return Section({
        dataSection: 'source-quality',
        title: 'Source Quality Banner',
        children:
            parts.length > 0
                ? parts.join(' ')
                : '<span data-part="no-data">Source data provenance not available.</span>',
    });
}

function buildActions(
    high: FlakinessEntry[],
    thresholds: FlakinessThresholds,
    flakyTestRate: number | undefined,
): string {
    const actions: Array<{ severity: 'error' | 'warn' | 'info'; text: string }> = [];

    if (high.length > 0) {
        // Count extreme flakiness
        const extreme = high.filter((f) => Math.round(f.rate * 100) >= thresholds.highFlakinessPct);
        const moderate = high.filter((f) => Math.round(f.rate * 100) < thresholds.highFlakinessPct);

        if (extreme.length > 0) {
            actions.push({
                severity: 'error',
                text: `${extreme.length} test(s) have extreme flakiness (>=${thresholds.highFlakinessPct}%). Consider quarantining until root cause is identified: ${extreme
                    .slice(0, 3)
                    .map((f) => sanitizeHtml(f.title))
                    .join(', ')}.`,
            });
        }

        if (moderate.length > 0) {
            actions.push({
                severity: 'warn',
                text: `${moderate.length} test(s) have moderate flakiness. Review test isolation — check for shared state, timing dependencies, and external service mocking.`,
            });
        }

        // C-5: flaky rate context from SSOT (not cumulative denominator)
        if (flakyTestRate !== undefined && flakyTestRate > 5) {
            actions.push({
                severity: 'warn',
                text: `Flaky rate is ${Math.round(flakyTestRate)}% of qualifying tests. This indicates systemic stability issues.`,
            });
        }
    }

    // Always add threshold context
    actions.push({
        severity: 'info',
        text: `Flakiness threshold: >${thresholds.thresholdPct}%. Tests below this threshold are considered stable.`,
    });

    return Section({
        dataSection: 'actions',
        title: 'Recommended Actions',
        children: RecommendedActions({ actions }),
    });
}
