/**
 * Impact-Aware Pipeline Alert — HTML rendering layer.
 *
 * Receives computed ImpactAlertResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module impact-alert-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { MetricCard, MetricGrid, Card } from '../primitives/index.js';
import { rootLogger } from '../logger.js';
import type { ImpactAlertResult, ImpactAlert, AlertSeverity } from './impact-alert.js';

const SEVERITY_MAP: Record<AlertSeverity, 'error' | 'warn' | 'info'> = {
    critical: 'error',
    warning: 'warn',
    info: 'info',
};

function renderAlertCard(alert: ImpactAlert): string {
    const cardSeverity = SEVERITY_MAP[alert.severity];
    return Card({
        severity: cardSeverity,
        children:
            '<div style="font-weight:600;margin-bottom:8px">' +
            sanitizeHtml(alert.title) +
            '</div>' +
            '<div style="margin-bottom:8px">' +
            sanitizeHtml(alert.message) +
            '</div>' +
            '<div style="font-size:0.85rem;color:var(--color-text-secondary);margin-bottom:4px">' +
            '<strong>Affected:</strong> ' +
            sanitizeHtml(alert.affectedArea) +
            '</div>' +
            '<div style="font-size:0.85rem;color:var(--color-text-secondary)">' +
            '<strong>Recommendation:</strong> ' +
            sanitizeHtml(alert.recommendation) +
            '</div>',
    });
}

export function generateImpactAlertHtml(result: ImpactAlertResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            rootLogger.error(
                'Impact alert result is null or undefined. Verify pipeline metrics and coverage data are being collected.',
            );
            return buildErrorPage('Error generating report', 'Impact Alert Report Error');
        }

        const pageTitle = title || 'Impact-Aware Pipeline Alert';

        const summaryCards = MetricGrid({
            children:
                MetricCard({ label: 'Total Alerts', value: String(result.alerts.length) }) +
                MetricCard({
                    label: 'Critical',
                    value: String(result.criticalCount),
                    severity: 'error',
                }) +
                MetricCard({
                    label: 'Warning',
                    value: String(result.warningCount),
                    severity: 'warn',
                }) +
                MetricCard({
                    label: 'Info',
                    value: String(result.infoCount),
                    severity: 'info',
                }),
        });

        let alertsHtml: string;
        if (result.alerts.length === 0) {
            alertsHtml = '<p style="color:var(--color-text-muted)">No alerts to display.</p>';
        } else {
            alertsHtml = result.alerts.map(renderAlertCard).join('');
        }

        const bodyContent = '<h1>' + sanitizeHtml(pageTitle) + '</h1>' + summaryCards + alertsHtml;

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Impact-Aware Pipeline Alert',
        });
    } catch (err) {
        const msg = String(err);
        rootLogger.error(
            'Failed to generate impact alert HTML: ' + msg + '. Check html-factory dependencies and try again.',
        );
        return buildErrorPage('Error generating report', 'Impact Alert Report Error');
    }
}
