/**
 * Impact-Aware Pipeline Alert — HTML rendering layer.
 *
 * Receives computed ImpactAlertResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module impact-alert-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { MetricCard, MetricGrid, Card, Section, EmptyState, RecommendedActions } from '../primitives/index.js';
import { rootLogger } from '../logger.js';
import type { ImpactAlertResult, ImpactAlert, AlertSeverity } from './impact-alert.js';

const SEVERITY_MAP: Record<AlertSeverity, 'error' | 'warn' | 'info'> = {
    critical: 'error',
    warning: 'warn',
    info: 'info',
};

const SEVERITY_ICON: Record<AlertSeverity, string> = {
    critical: '\u{1F534}',
    warning: '\u{1F7E1}',
    info: '\u{1F535}',
};

function renderAlertCard(alert: ImpactAlert): string {
    const cardSeverity = SEVERITY_MAP[alert.severity];
    const icon = SEVERITY_ICON[alert.severity];

    return Card({
        severity: cardSeverity,
        children:
            `<div data-part="alert-header">${icon} <strong>${sanitizeHtml(alert.title)}</strong></div>` +
            `<div data-part="alert-message">${sanitizeHtml(alert.message)}</div>` +
            `<div data-part="alert-affected"><strong>Affected:</strong> ${sanitizeHtml(alert.affectedArea)}</div>` +
            `<div data-part="alert-recommendation"><strong>Action Required:</strong> ${sanitizeHtml(alert.recommendation)}</div>`,
    });
}

export function generateImpactAlertHtml(result: ImpactAlertResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            rootLogger.error(
                'Impact alert result is null or undefined. Verify pipeline metrics and coverage data are being collected.',
            );
            return buildErrorPage('Error generating report', 'Impact Alert Report Error');
        }

        const pageTitle = title || 'Impact-Aware Pipeline Alert';

        const bodyContent = wrapContainer(
            pageTitle,
            buildMetricSummary(result) + buildAlerts(result) + buildRecommendedActions(result),
        );

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Impact-Aware Pipeline Alert',
        });
    } catch (err) {
        const msg = String(err);
        rootLogger.error(
            'Failed to generate impact alert HTML: ' + msg + '. Check html-factory dependencies and try again.',
        );
        return buildErrorPage('Error generating report', 'Impact Alert Report Error');
    }
}

function wrapContainer(pageTitle: string, children: string): string {
    return `<div data-component="container" data-dashboard="impact-alert">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        ${children}
    </div>`;
}

function buildMetricSummary(result: ImpactAlertResult): string {
    // Group alerts by affected area for better visibility
    const affectedAreas = new Map<string, number>();
    for (const alert of result.alerts) {
        const count = affectedAreas.get(alert.affectedArea) || 0;
        affectedAreas.set(alert.affectedArea, count + 1);
    }

    return Section({
        dataSection: 'summary',
        title: 'Summary',
        children: MetricGrid({
            children:
                MetricCard({ label: 'Total Alerts', value: String(result.alerts.length) }) +
                MetricCard({
                    label: 'Critical',
                    value: String(result.criticalCount),
                    severity: 'error',
                }) +
                MetricCard({
                    label: 'Warning',
                    value: String(result.warningCount),
                    severity: 'warn',
                }) +
                MetricCard({
                    label: 'Info',
                    value: String(result.infoCount),
                    severity: 'info',
                }),
        }),
    });
}

function buildAlerts(result: ImpactAlertResult): string {
    if (result.alerts.length === 0) {
        return EmptyState({
            title: 'No alerts to display',
            description:
                'The impact alert report contains no alerts. This may indicate all pipeline stages are operating within acceptable thresholds.',
            action: 'Verify that pipeline metrics (coverage, performance, test results) are being collected and thresholds are configured.',
        });
    }

    // Sort by severity (critical first)
    const sorted = [...result.alerts].sort((a, b) => {
        const order: Record<string, number> = { critical: 0, warning: 1, info: 2 };
        return (order[a.severity] ?? 3) - (order[b.severity] ?? 3);
    });

    return Section({
        dataSection: 'alerts',
        title: 'Alerts',
        children: sorted.map(renderAlertCard).join(''),
    });
}

function buildRecommendedActions(result: ImpactAlertResult): string {
    const actions: Array<{ severity: 'error' | 'warn' | 'info'; text: string }> = [];

    // Action 1: Critical alerts
    if (result.criticalCount > 0) {
        const criticalAlerts = result.alerts.filter((a) => a.severity === 'critical');
        const areas = criticalAlerts.map((a) => sanitizeHtml(a.affectedArea)).join(', ');
        actions.push({
            severity: 'error',
            text: `${result.criticalCount} critical alert(s) detected in: ${areas}. Immediate action required to prevent pipeline failures.`,
        });
    }

    // Action 2: Warning alerts
    if (result.warningCount > 0) {
        const warningAlerts = result.alerts.filter((a) => a.severity === 'warning');
        const areas = warningAlerts.map((a) => sanitizeHtml(a.affectedArea)).join(', ');
        actions.push({
            severity: 'warn',
            text: `${result.warningCount} warning alert(s) detected in: ${areas}. Review pipeline configuration and thresholds.`,
        });
    }

    // Action 3: High alert count
    if (result.alerts.length > 10) {
        actions.push({
            severity: 'warn',
            text: `${result.alerts.length} alerts detected. Consider adjusting alert thresholds to reduce noise.`,
        });
    }

    // Default action if no issues found
    if (actions.length === 0) {
        actions.push({
            severity: 'info',
            text: 'No critical alerts detected. Pipeline is operating within acceptable thresholds.',
        });
    }

    return Section({
        dataSection: 'actions',
        title: 'Recommended Actions',
        children: RecommendedActions({ actions }),
    });
}
