/**
 * Impact-Aware Pipeline Alert — HTML rendering layer.
 *
 * Receives computed ImpactAlertResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module impact-alert-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { MetricCard, MetricGrid, Card, Section, EmptyState } from '../primitives/index.js';
import { rootLogger } from '../logger.js';
import type { ImpactAlertResult, ImpactAlert, AlertSeverity } from './impact-alert.js';

const SEVERITY_MAP: Record<AlertSeverity, 'error' | 'warn' | 'info'> = {
    critical: 'error',
    warning: 'warn',
    info: 'info',
};

function renderAlertCard(alert: ImpactAlert): string {
    const cardSeverity = SEVERITY_MAP[alert.severity];
    return Card({
        severity: cardSeverity,
        children:
            `<div data-part="alert-title">${sanitizeHtml(alert.title)}</div>` +
            `<div data-part="alert-message">${sanitizeHtml(alert.message)}</div>` +
            `<div data-part="alert-affected"><strong>Affected:</strong> ${sanitizeHtml(alert.affectedArea)}</div>` +
            `<div data-part="alert-recommendation"><strong>Recommendation:</strong> ${sanitizeHtml(alert.recommendation)}</div>`,
    });
}

export function generateImpactAlertHtml(result: ImpactAlertResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            rootLogger.error(
                'Impact alert result is null or undefined. Verify pipeline metrics and coverage data are being collected.',
            );
            return buildErrorPage('Error generating report', 'Impact Alert Report Error');
        }

        const pageTitle = title || 'Impact-Aware Pipeline Alert';

        const bodyContent = wrapContainer(pageTitle, buildMetricSummary(result) + buildAlerts(result));

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Impact-Aware Pipeline Alert',
        });
    } catch (err) {
        const msg = String(err);
        rootLogger.error(
            'Failed to generate impact alert HTML: ' + msg + '. Check html-factory dependencies and try again.',
        );
        return buildErrorPage('Error generating report', 'Impact Alert Report Error');
    }
}

function wrapContainer(pageTitle: string, children: string): string {
    return `<div data-component="container" data-dashboard="impact-alert">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        ${children}
    </div>`;
}

function buildMetricSummary(result: ImpactAlertResult): string {
    return Section({
        dataSection: 'summary',
        children: MetricGrid({
            children:
                MetricCard({ label: 'Total Alerts', value: String(result.alerts.length) }) +
                MetricCard({
                    label: 'Critical',
                    value: String(result.criticalCount),
                    severity: 'error',
                }) +
                MetricCard({
                    label: 'Warning',
                    value: String(result.warningCount),
                    severity: 'warn',
                }) +
                MetricCard({
                    label: 'Info',
                    value: String(result.infoCount),
                    severity: 'info',
                }),
        }),
    });
}

function buildAlerts(result: ImpactAlertResult): string {
    if (result.alerts.length === 0) {
        return EmptyState({
            title: 'No alerts to display',
            description:
                'The impact alert report contains no alerts. This may indicate all pipeline stages are operating within acceptable thresholds.',
            action: 'Verify that pipeline metrics (coverage, performance, test results) are being collected and thresholds are configured.',
        });
    }

    return Section({
        dataSection: 'alerts',
        title: 'Alerts',
        children: result.alerts.map(renderAlertCard).join(''),
    });
}
