/**
 * Incident Investigation Report — HTML rendering layer.
 *
 * Receives computed IncidentReport and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module incident-report-renderer
 */

import { rootLogger } from '../logger.js';
import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import {
    MetricCard,
    MetricGrid,
    Card,
    Section,
    EmptyState,
    RecommendedActions,
    SeverityBadge,
} from '../primitives/index.js';
import { extractErrorMessage } from '../ui/prompt-errors.js';
import { icon } from '../icons.js';
import type { IncidentReport } from './incident-report.js';

const HIGH_SEVERITY_TARGET = 0;
const MEDIUM_SEVERITY_TARGET = 0;
const LOW_SEVERITY_TARGET = 0;

function severityToCardSeverity(s: string): 'error' | 'warn' | 'info' | 'default' {
    if (s === 'high') return 'error';
    if (s === 'medium') return 'warn';
    if (s === 'low') return 'info';
    return 'default';
}

function eventTypeToLabel(type: string): string {
    const labels = new Map([
        ['failure', 'Failure'],
        ['regression', 'Regression'],
        ['coverage_gap', 'Coverage Gap'],
        ['seasonality', 'Seasonality'],
    ]);
    const icons = new Map([
        ['failure', 'x-circle'],
        ['regression', 'trending-up'],
        ['coverage_gap', 'bar-chart'],
        ['seasonality', 'calendar'],
    ]);
    const iconKey = icons.get(type);
    const iconSvg = iconKey ? icon(iconKey, 14) : '';
    return `${iconSvg} ${labels.get(type) || type}`;
}

export function generateIncidentReportHtml(report: IncidentReport | null | undefined, title?: string): string {
    try {
        if (!report) {
            rootLogger.error(
                'Incident report is null or undefined. Ensure a valid IncidentReport object is passed to generateIncidentReportHtml.',
            );
            return buildErrorPage('Error generating report', 'Error generating incident investigation report');
        }

        const pageTitle = title || 'Incident Investigation Report';

        const bodyContent = wrapContainer(
            pageTitle,
            SeverityBadge({ severity: report.overallSeverity, children: report.overallSeverity }) +
                buildMetricSummary(report) +
                buildSummary(report) +
                buildEvents(report) +
                buildPerTypeSummary(report) +
                buildRecommendedActions(report),
            report.timestamp,
        );

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Incident Investigation Report',
        });
    } catch (err: unknown) {
        rootLogger.error(
            'Failed to generate incident report HTML: ' +
                extractErrorMessage(err) +
                '. Verify that input data (failRate, passRate, regressionCount) is valid and the html-factory module is working correctly.',
        );
        return buildErrorPage('Error generating report', 'Error generating incident investigation report');
    }
}

function wrapContainer(pageTitle: string, children: string, timestamp: string): string {
    return `<div data-component="container" data-dashboard="incident-report">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        <div data-part="timestamp">${sanitizeHtml(timestamp)}</div>
        ${children}
    </div>`;
}

function buildMetricSummary(report: IncidentReport): string {
    const overallSeverity = report.overallSeverity;
    let overallSeveritySeverity: 'error' | 'warn' | 'info' | 'default';
    if (overallSeverity === 'high') overallSeveritySeverity = 'error';
    else if (overallSeverity === 'medium') overallSeveritySeverity = 'warn';
    else if (overallSeverity === 'low') overallSeveritySeverity = 'info';
    else overallSeveritySeverity = 'default';

    return Section({
        dataSection: 'summary',
        title: 'Summary',
        children: MetricGrid({
            children:
                MetricCard({
                    label: 'Overall Severity',
                    value: overallSeverity.charAt(0).toUpperCase() + overallSeverity.slice(1),
                    severity: overallSeveritySeverity,
                    target: 'target: none',
                }) +
                MetricCard({ label: 'Total Events', value: String(report.eventCount) }) +
                MetricCard({
                    label: 'High Severity',
                    value: String(report.highCount),
                    severity: report.highCount > 0 ? 'error' : 'default',
                    target: `target: ${HIGH_SEVERITY_TARGET}`,
                }) +
                MetricCard({
                    label: 'Medium Severity',
                    value: String(report.mediumCount),
                    severity: report.mediumCount > 0 ? 'warn' : 'default',
                    target: `target: ${MEDIUM_SEVERITY_TARGET}`,
                }) +
                MetricCard({
                    label: 'Low Severity',
                    value: String(report.lowCount),
                    severity: report.lowCount > 0 ? 'info' : 'default',
                    target: `target: ${LOW_SEVERITY_TARGET}`,
                }),
        }),
    });
}

function buildSummary(report: IncidentReport): string {
    return `<p data-part="summary">${sanitizeHtml(report.summary)}</p>`;
}

function buildEvents(report: IncidentReport): string {
    if (report.events.length === 0) {
        return EmptyState({
            title: 'No incidents to display',
            description: 'The incident report contains no events. This may indicate no recent failures were detected.',
            action: 'Verify that the test suite is running and failures are being captured by the monitoring pipeline.',
        });
    }

    // Group events by date for better temporal context
    const eventsByDate = new Map<string, typeof report.events>();
    for (const event of report.events) {
        const dateKey = event.date.split('T')[0] || event.date;
        const existing = eventsByDate.get(dateKey) || [];
        existing.push(event);
        eventsByDate.set(dateKey, existing);
    }

    let eventsHtml = '';
    for (const [date, events] of eventsByDate) {
        const eventCards = events
            .map((event) =>
                Card({
                    severity: severityToCardSeverity(event.severity),
                    children:
                        `<div data-part="event-type">${eventTypeToLabel(event.type)}</div>` +
                        `<div data-part="event-title">${sanitizeHtml(event.title)}</div>` +
                        `<div data-part="event-description">${sanitizeHtml(event.description)}</div>`,
                }),
            )
            .join('');

        eventsHtml += `<h3>${sanitizeHtml(date)}</h3>${eventCards}`;
    }

    return Section({
        dataSection: 'events',
        title: 'Events Timeline',
        children: eventsHtml,
    });
}

function buildPerTypeSummary(report: IncidentReport): string {
    const typeCounts: Record<string, number> = {};
    for (const event of report.events) {
        typeCounts[event.type] = (typeCounts[event.type] ?? 0) + 1;
    }

    const labels = new Map<string, string>([
        ['failure', 'Failures'],
        ['regression', 'Regressions'],
        ['coverage_gap', 'Coverage Gaps'],
        ['seasonality', 'Seasonality Events'],
    ]);

    const children = Object.entries(typeCounts)
        .map(([type, count]) => MetricCard({ label: labels.get(type) ?? type, value: String(count) }))
        .join('');

    // Rule 25: explicit no-data (no per-type counts) instead of silent omission.
    if (!children) {
        return EmptyState({
            title: 'No incident type data available',
            description: 'Per-type count summary requires incidents classified by type. No type data was found.',
            action: 'Classify incidents by type so the per-type summary can be rendered.',
            icon: icon('bar-chart', 16),
        });
    }

    return Section({
        dataSection: 'per-type',
        title: 'Per-Type Count Summary',
        children: MetricGrid({ children }),
    });
}

function buildRecommendedActions(report: IncidentReport): string {
    const actions: Array<{ severity: 'error' | 'warn' | 'info'; text: string }> = [];

    // Action 1: High severity incidents
    if (report.highCount > 0) {
        actions.push({
            severity: 'error',
            text: `${report.highCount} high-severity incident(s) detected. Immediate investigation required for critical failures. Notify on-call engineer and create incident ticket.`,
        });
    }

    // Action 2: Medium severity incidents
    if (report.mediumCount > 0) {
        actions.push({
            severity: 'warn',
            text: `${report.mediumCount} medium-severity incident(s) detected. Review and prioritize remediation within next sprint.`,
        });
    }

    // Action 3: High incident count
    if (report.eventCount > 5) {
        actions.push({
            severity: 'warn',
            text: `${report.eventCount} incidents detected. Consider implementing additional test coverage or monitoring to prevent future incidents.`,
        });
    }

    // Action 4: Regression events
    const regressionCount = report.events.filter((e) => e.type === 'regression').length;
    if (regressionCount > 0) {
        actions.push({
            severity: 'error',
            text: `${regressionCount} regression(s) detected. Review recent code changes and implement regression test coverage.`,
        });
    }

    // Default action if no issues found
    if (actions.length === 0) {
        actions.push({
            severity: 'info',
            text: 'No critical incidents detected. Continue monitoring for regressions.',
        });
    }

    return Section({
        dataSection: 'actions',
        title: 'Recommended Actions',
        children: RecommendedActions({ actions }),
    });
}
