/**
 * Integration tests — HTML Report (FT-17)
 *
 * Validates the HTML report orchestrator end-to-end:
 * - generateHtmlReport with/without options
 * - generateCoverageHtml with varying epics
 * - generateReportWithFallback error handling
 * - Key sections present: summary, chart, table, footer
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('../../logger.js', () => ({
    rootLogger: { error: vi.fn(), info: vi.fn(), child: vi.fn().mockReturnThis() },
}));

vi.mock('../../config.js', () => ({
    default: { get: vi.fn(() => '') },
    get: vi.fn(() => ''),
}));

vi.mock('../../html-factory.js', async (importOriginal) => {
    const actual = await importOriginal<typeof import('../../html-factory.js')>();
    return { ...actual, buildHtmlPage: vi.fn(actual.buildHtmlPage) };
});

describe('Integration: HTML Report (FT-17)', () => {
    beforeEach(() => {
        vi.restoreAllMocks();
    });

    describe('FT-17a: generateHtmlReport', () => {
        it('returns complete HTML document', async () => {
            const { generateHtmlReport } = await import('../../report-html.js');
            const tests = [
                { title: 'Login Test', state: 'passed' as const, duration: 1.2, fullTitle: 'Auth > Login' },
                { title: 'Fail Test', state: 'failed' as const, duration: 0.5, fullTitle: 'Auth > Fail' },
            ];
            const html = generateHtmlReport(tests, { title: 'FT-17 Test Report' });

            expect(html).toContain('<!DOCTYPE html>');
            expect(html).toContain('</html>');
            expect(html).toContain('FT-17 Test Report');
            expect(html).toContain('Login Test');
            expect(html).toContain('Fail Test');
            expect(html).toContain('Generated by QA Tools');
        });

        it('handles empty test array gracefully', async () => {
            const { generateHtmlReport } = await import('../../report-html.js');
            const html = generateHtmlReport([], { title: 'Empty' });

            expect(html).toContain('<!DOCTYPE html>');
            expect(html).toContain('Empty');
            expect(html).not.toContain('Error generating report');
        });

        it('includes health score section when provided', async () => {
            const { generateHtmlReport } = await import('../../report-html.js');
            const tests = [{ title: 'T1', state: 'passed' as const, duration: 1 }];
            const healthScore = {
                overall: 85,
                grade: 'good' as const,
                qualityGate: 'pass' as const,
                runCount: 10,
                timestamp: '2026-06-01T00:00:00Z',
                dimensions: {
                    passRate: { score: 90, status: 'pass' as const },
                    flakyRate: { score: 85, status: 'pass' as const },
                    coverage: { score: 80, status: 'pass' as const },
                    suiteSpeed: { score: 75, status: 'fail' as const },
                    executionRate: { score: 100, status: 'pass' as const },
                },
            };
            const html = generateHtmlReport(tests, { title: 'Health', healthScore });

            expect(html).toContain('Test Suite Health');
            expect(html).toContain('Quality Gate: Pass');
        });

        it('includes quality gate section when gate fails', async () => {
            const { generateHtmlReport } = await import('../../report-html.js');
            const tests = [
                { title: 'Pass', state: 'passed' as const, duration: 1 },
                { title: 'Fail', state: 'failed' as const, duration: 2 },
            ];
            const html = generateHtmlReport(tests, { title: 'QG', qualityGate: 99 });

            expect(html).toContain('Quality Gate');
        });

        it('renders multi-run tabs', async () => {
            const { generateHtmlReport } = await import('../../report-html.js');
            const chromeTests = [{ title: 'C1', state: 'passed' as const, duration: 1 }];
            const firefoxTests = [{ title: 'F1', state: 'passed' as const, duration: 2 }];
            const html = generateHtmlReport(chromeTests, {
                title: 'Multi',
                runs: [
                    { name: 'Chrome', tests: chromeTests },
                    { name: 'Firefox', tests: firefoxTests },
                ],
            });

            expect(html).toContain('Chrome');
            expect(html).toContain('Firefox');
            expect(html).toContain('switchTab');
        });
    });

    describe('FT-17b: generateCoverageHtml', () => {
        it('returns complete HTML document', async () => {
            const { generateCoverageHtml } = await import('../../report-html.js');
            const epics = [
                {
                    key: 'EPIC-1',
                    summary: 'First Epic',
                    issues: [
                        { key: 'T-1', summary: 'Task 1', status: 'Done', type: 'Task' },
                        { key: 'T-2', summary: 'Task 2', status: 'In Progress', type: 'Task' },
                    ],
                },
            ];
            const html = generateCoverageHtml(epics, 'Coverage Test');

            expect(html).toContain('Coverage Test');
            expect(html).toContain('EPIC-1');
            expect(html).toContain('T-1');
            expect(html).toContain('T-2');
        });

        it('shows per-epic close percentage', async () => {
            const { generateCoverageHtml } = await import('../../report-html.js');
            const epics = [
                {
                    key: 'EPIC-A',
                    summary: 'Half closed',
                    issues: [
                        { key: 'A-1', summary: 'Done', status: 'Done', type: 'Task' },
                        { key: 'A-2', summary: 'Open', status: 'Open', type: 'Bug' },
                    ],
                },
                {
                    key: 'EPIC-B',
                    summary: 'All open',
                    issues: [{ key: 'B-1', summary: 'To Do', status: 'To Do', type: 'Task' }],
                },
            ];
            const html = generateCoverageHtml(epics);

            expect(html).toContain('50.0');
            expect(html).toContain('0.0');
        });
    });

    describe('FT-17c: error fallback', () => {
        it('returns buildErrorPage when buildHtmlPage throws', async () => {
            const { generateHtmlReport } = await import('../../report-html.js');
            const { buildHtmlPage } = await import('../../html-factory.js');
            const { rootLogger } = await import('../../logger.js');

            vi.mocked(buildHtmlPage).mockImplementationOnce(() => {
                throw new Error('page assembly failed');
            });

            const html = generateHtmlReport([{ title: 'T1', state: 'passed' as const, duration: 1 }], {
                title: 'Error Test',
            });

            expect(html).toContain('Error generating report');
            expect(vi.spyOn(rootLogger, 'error')).toHaveBeenCalledWith(
                expect.stringContaining('Failed to generate HTML report'),
            );
        });
    });

    describe('FT-17d: generateCoverageHtml with empty epics', () => {
        it('handles empty epics gracefully', async () => {
            const { generateCoverageHtml } = await import('../../report-html.js');
            const html = generateCoverageHtml([]);

            expect(html).toContain('<!DOCTYPE html>');
            expect(html).not.toContain('Error generating coverage report');
        });
    });
});
