/**
 * Integration tests — HTML Report (FT-17)
 *
 * Validates the HTML report orchestrator end-to-end:
 * - generateHtmlReport with/without options
 * - Key sections present: summary, chart, table, footer
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { FlatTest } from '../../result_parser.js';
import type { ComputedMetrics } from '../../types/data-hub.js';

function computedFor(tests: FlatTest[]): ComputedMetrics {
    const passed = tests.filter((t) => t.state === 'passed').length;
    const failed = tests.filter((t) => t.state === 'failed').length;
    const skipped = tests.filter((t) => t.state === 'skipped').length;
    const totalDuration = tests.reduce((s: number, t: FlatTest) => s + t.duration, 0);
    return {
        passRate: passed + failed > 0 ? (passed / (passed + failed)) * 100 : 0,
        avgDuration: 0,
        suiteSpeedP95: 0,
        flakyRate: [],
        coverage: 0,
        pipelineCost: { totalRuns: 0, totalCostUsd: 0, billableMinutes: 0 },
        defectTrends: [],
        branchBreakdown: {},
        topFailingJobs: [],
        topFailureReasons: [],
        releaseScore: { overall: 0, grade: 'unknown' as const, metrics: {} },
        quarantineStatus: { blocked: 0, quarantined: 0, passed: 0 },
        testPassRate: passed + failed > 0 ? (passed / (passed + failed)) * 100 : 0,
        testCounts: { passed, failed, skipped, total: tests.length },
        framework: '',
        metricsRuns: [
            {
                timestamp: '2026-05-31T00:00:00Z',
                project: 'qa-tools',
                total: tests.length,
                passed,
                failed,
                skipped,
                duration: totalDuration,
                tests,
            },
        ],
    } as unknown as ComputedMetrics;
}

vi.mock('../../logger.js', () => ({
    rootLogger: { error: vi.fn(), info: vi.fn(), child: vi.fn().mockReturnThis() },
}));

vi.mock('../../config-accessor.js', () => ({
    default: { get: vi.fn(() => '') },
    get: vi.fn(() => ''),
}));

vi.mock('../../report/html-factory.js', async (importOriginal) => {
    const actual = await importOriginal<typeof import('../../report/html-factory.js')>();
    return { ...actual, buildHtmlPage: vi.fn(actual.buildHtmlPage) };
});

vi.mock('../../ui/cli_base.js', () => ({
    sanitizeUrl: (url: string) => url,
}));

describe('Integration: HTML Report (FT-17)', () => {
    beforeEach(() => {
        vi.restoreAllMocks();
    });

    describe('FT-17a: generateHtmlReport', () => {
        it('returns complete HTML document', { timeout: 15000 }, async () => {
            expect.hasAssertions();

            const { generateHtmlReport } = await import('../../report/report-html.js');
            const tests = [
                { title: 'Login Test', state: 'passed' as const, duration: 1.2, fullTitle: 'Auth > Login' },
                { title: 'Fail Test', state: 'failed' as const, duration: 0.5, fullTitle: 'Auth > Fail' },
            ];
            const html = generateHtmlReport(tests, { computed: computedFor(tests), title: 'FT-17 Test Report' });

            expect(html).toContain('<!DOCTYPE html>');
            expect(html).toContain('</html>');
            expect(html).toContain('FT-17 Test Report');
            expect(html).toContain('Login Test');
            expect(html).toContain('Fail Test');
            expect(html).toContain('Generated by QA Tools');
        });

        it('handles empty test array gracefully', async () => {
            expect.hasAssertions();

            const { generateHtmlReport } = await import('../../report/report-html.js');
            const html = generateHtmlReport([], { computed: computedFor([]), title: 'Empty' });

            expect(html).toContain('<!DOCTYPE html>');
            expect(html).toContain('Empty');
            expect(html).not.toContain('Error generating report');
        });

        it('includes health score section when provided', async () => {
            expect.hasAssertions();

            const { generateHtmlReport } = await import('../../report/report-html.js');
            const tests = [{ title: 'T1', state: 'passed' as const, duration: 1 }];
            const healthScore = {
                overall: 85,
                grade: 'good' as const,
                qualityGate: 'pass' as const,
                runCount: 10,
                timestamp: '2026-06-01T00:00:00Z',
                dimensions: {
                    passRate: { score: 90, status: 'pass' as const, available: true },
                    flakyRate: { score: 85, status: 'pass' as const, available: true },
                    coverage: { score: 80, status: 'pass' as const, available: true },
                    suiteSpeed: { score: 75, status: 'fail' as const, available: true },
                    executionRate: { score: 100, status: 'pass' as const, available: true },
                },
            };
            const html = generateHtmlReport(tests, { computed: computedFor(tests), title: 'Health', healthScore });

            expect(html).toContain('Test Suite Health');
            expect(html).toContain('Quality Gate: Pass');
        });

        it('includes quality gate section when gate fails', async () => {
            expect.hasAssertions();

            const { generateHtmlReport } = await import('../../report/report-html.js');
            const tests = [
                { title: 'Pass', state: 'passed' as const, duration: 1 },
                { title: 'Fail', state: 'failed' as const, duration: 2 },
            ];
            const html = generateHtmlReport(tests, { computed: computedFor(tests), title: 'QG', qualityGate: 99 });

            expect(html).toContain('Quality Gate');
        });

        it('renders multi-run tabs', async () => {
            expect.hasAssertions();

            const { generateHtmlReport } = await import('../../report/report-html.js');
            const chromeTests = [{ title: 'C1', state: 'passed' as const, duration: 1 }];
            const firefoxTests = [{ title: 'F1', state: 'passed' as const, duration: 2 }];
            const html = generateHtmlReport(chromeTests, {
                computed: computedFor(chromeTests),
                title: 'Multi',
                runs: [
                    { name: 'Chrome', tests: chromeTests },
                    { name: 'Firefox', tests: firefoxTests },
                ],
            });

            expect(html).toContain('Chrome');
            expect(html).toContain('Firefox');
            expect(html).toContain('switchTab');
        });
    });

    describe('FT-17c: error fallback', () => {
        it('returns buildErrorPage when buildHtmlPage throws', async () => {
            expect.hasAssertions();

            const { generateHtmlReport } = await import('../../report/report-html.js');
            const { buildHtmlPage } = await import('../../report/html-factory.js');
            const { rootLogger } = await import('../../logger.js');

            vi.mocked(buildHtmlPage).mockImplementationOnce(() => {
                throw new Error('page assembly failed');
            });

            const html = generateHtmlReport([{ title: 'T1', state: 'passed' as const, duration: 1 }], {
                computed: computedFor([{ title: 'T1', state: 'passed' as const, duration: 1 }]),
                title: 'Error Test',
            });

            expect(html).toContain('Error generating report');
            expect(vi.spyOn(rootLogger, 'error')).toHaveBeenCalledWith(
                expect.stringContaining('Failed to generate HTML report'),
            );
        });
    });
});
