/**
 * Pipeline Cost Analytics — HTML renderer.
 *
 * Extracted from pipeline-cost.ts (compute) to separate concerns.
 * This module handles ONLY HTML generation; all business logic remains in pipeline-cost.ts.
 *
 * @module pipeline-cost-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from '../report/html-factory.js';
import { buildCss } from '../report/report-styles.js';
import { MetricCard, MetricGrid, DataTable, Section, EmptyState, RecommendedActions } from '../primitives/index.js';
import type { TableColumn, TableRow } from '../primitives/index.js';
import { rootLogger } from '../logger.js';
import type { PipelineCostResult } from './pipeline-cost.js';

const TOTAL_COST_WARN_THRESHOLD = 50;
const TOTAL_COST_ERROR_THRESHOLD = 100;
const AVG_COST_PER_RUN_WARN_THRESHOLD = 10;

function formatCurrency(value: number): string {
    return '$' + value.toFixed(2);
}

function formatDuration(seconds: number): string {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    if (m >= 60) {
        const h = Math.floor(m / 60);
        const rm = m % 60;
        return h + 'h ' + rm + 'm ' + s.toFixed(0) + 's';
    }
    return m + 'm ' + s.toFixed(0) + 's';
}

export function generatePipelineCostHtml(result: PipelineCostResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            rootLogger.error(
                'Pipeline cost result is null or undefined. Ensure calculatePipelineCost is called before generatePipelineCostHtml.',
            );
            return buildErrorPage(
                'Error generating report — no pipeline cost data found',
                'Pipeline Cost Report Error',
            );
        }

        const pageTitle = title || 'Pipeline Cost Analytics';

        let bodyContent =
            `<div data-dashboard="pipeline-cost">` +
            `<h1>${sanitizeHtml(pageTitle)}</h1>` +
            `<div data-part="timestamp">${sanitizeHtml(result.timestamp)}</div>` +
            buildMetricSummary(result);

        if (result.costByRun.length === 0) {
            bodyContent += EmptyState({
                title: 'No pipeline run data available',
                description: 'No pipeline execution data is available for cost analysis.',
                action: 'Run CI/CD pipelines to generate cost data.',
                icon: '\u{1F4B0}',
            });
        } else {
            bodyContent += buildCostTable(result);
        }

        bodyContent += buildRecommendedActions(result) + `</div>`;

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Pipeline Cost Analytics',
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error('Failed to generate pipeline cost HTML: ' + msg);
        return buildErrorPage(
            'Error generating report — check pipeline cost data and try again',
            'Pipeline Cost Report Error',
        );
    }
}

function buildMetricSummary(result: PipelineCostResult): string {
    const failedRuns = result.costByRun.filter((r) => r.status === 'failed');
    const failedCost = failedRuns.reduce((sum, r) => sum + r.cost, 0);

    return Section({
        dataSection: 'summary',
        title: 'Summary',
        children: MetricGrid({
            children:
                MetricCard({
                    label: 'Total Cost',
                    value: formatCurrency(result.totalCost),
                    severity: (() => {
                        if (result.totalCost > TOTAL_COST_ERROR_THRESHOLD) return 'error';
                        if (result.totalCost > TOTAL_COST_WARN_THRESHOLD) return 'warn';
                        return 'info';
                    })(),
                    target: `target: <${formatCurrency(TOTAL_COST_WARN_THRESHOLD)}`,
                }) +
                MetricCard({
                    label: 'Avg Cost / Run',
                    value: formatCurrency(result.avgCostPerRun),
                    severity: result.avgCostPerRun > AVG_COST_PER_RUN_WARN_THRESHOLD ? 'warn' : 'info',
                    target: `target: <${formatCurrency(AVG_COST_PER_RUN_WARN_THRESHOLD)}`,
                }) +
                MetricCard({
                    label: 'Failed Cost',
                    value: formatCurrency(failedCost),
                    severity: failedCost > 0 ? 'error' : 'success',
                    trend: failedRuns.length > 0 ? `${failedRuns.length} failed run(s)` : '',
                    target: 'target: $0.00',
                }) +
                MetricCard({
                    label: 'Total Duration',
                    value: formatDuration(result.totalDurationSec),
                }) +
                MetricCard({
                    label: 'Run Count',
                    value: String(result.runCount),
                }),
        }),
    });
}

function buildCostTable(result: PipelineCostResult): string {
    // Sort by cost (most expensive first) for better visibility
    const sorted = [...result.costByRun].sort((a, b) => b.cost - a.cost);

    const columns: TableColumn[] = [
        { key: 'date', label: 'Date', width: '25%' },
        { key: 'duration', label: 'Duration', align: 'right' },
        { key: 'cost', label: 'Cost', align: 'right' },
        { key: 'status', label: 'Status' },
    ];

    const rows: TableRow[] = sorted.map((e, i) => {
        const dateStr = sanitizeHtml(new Date(e.timestamp).toLocaleDateString());

        return {
            key: String(i),
            cells: {
                date: dateStr,
                duration: formatDuration(e.durationSec),
                cost: formatCurrency(e.cost),
                status: sanitizeHtml(e.status),
            },
        };
    });

    return Section({
        dataSection: 'cost-breakdown',
        title: 'Cost Breakdown',
        children: DataTable({
            columns,
            rows,
            caption: 'Pipeline runs sorted by cost (highest first)',
        }),
    });
}

function buildRecommendedActions(result: PipelineCostResult): string {
    const actions: Array<{ severity: 'error' | 'warn' | 'info'; text: string }> = [];

    // Action 1: High total cost
    if (result.totalCost > 100) {
        actions.push({
            severity: 'error',
            text: `Total pipeline cost is ${formatCurrency(result.totalCost)}. Consider optimizing test execution time or reducing pipeline runs.`,
        });
    }

    // Action 2: High average cost per run
    if (result.avgCostPerRun > 10) {
        actions.push({
            severity: 'warn',
            text: `Average cost per run is ${formatCurrency(result.avgCostPerRun)}. Review pipeline configuration for cost reduction opportunities.`,
        });
    }

    // Action 3: Failed runs with cost impact
    const failedRuns = result.costByRun.filter((r) => r.status === 'failed');
    if (failedRuns.length > 0) {
        const failedCost = failedRuns.reduce((sum, r) => sum + r.cost, 0);
        actions.push({
            severity: 'warn',
            text: `${failedRuns.length} pipeline run(s) failed, wasting ${formatCurrency(failedCost)} in resources. Investigate failure causes to prevent future waste.`,
        });
    }

    // Action 4: Most expensive run
    if (result.costByRun.length > 0) {
        const firstRun = result.costByRun[0];
        if (firstRun) {
            const mostExpensive = result.costByRun.reduce((max, r) => (r.cost > max.cost ? r : max), firstRun);
            if (mostExpensive.cost > result.avgCostPerRun * 2) {
                actions.push({
                    severity: 'info',
                    text: `Most expensive run: ${formatCurrency(mostExpensive.cost)} on ${sanitizeHtml(new Date(mostExpensive.timestamp).toLocaleDateString())} (${formatDuration(mostExpensive.durationSec)}). Consider optimizing this run.`,
                });
            }
        }
    }

    // Default action if no issues found
    if (actions.length === 0) {
        actions.push({
            severity: 'info',
            text: 'Pipeline costs are within acceptable ranges. Continue monitoring.',
        });
    }

    return Section({
        dataSection: 'actions',
        title: 'Recommended Actions',
        children: RecommendedActions({ actions }),
    });
}
