/**
 * Release Readiness Score — HTML rendering layer.
 *
 * Receives computed ReleaseScoreResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module release-score-renderer
 */

import { buildHtmlPage } from '../report/html-factory.js';
import { buildCss } from '../report/report-styles.js';
import { sanitizeHtml } from '../escape.js';
import { Badge, MetricCard, MetricGrid, Section } from '../primitives/index.js';
import type { ReleaseScoreResult } from './release-score.js';

export function generateReleaseScoreHtml(result: ReleaseScoreResult): string {
    const bodyContent = wrapContainer(
        'Release Readiness Score',
        buildScoreSummary(result) + buildBreakdown(result) + buildRecommendation(result),
    );

    return buildHtmlPage({
        title: 'Release Readiness Score',
        styles: buildCss(),
        theme: 'system',
        bodyContent,
        footer: 'Generated by QA Tools',
    });
}

function wrapContainer(pageTitle: string, children: string): string {
    return `<div data-component="container" data-dashboard="release-score">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        ${children}
    </div>`;
}

function buildScoreSummary(result: ReleaseScoreResult): string {
    let scoreSeverity: 'success' | 'warn' | 'error';
    if (result.score >= 80) {
        scoreSeverity = 'success';
    } else if (result.score >= 50) {
        scoreSeverity = 'warn';
    } else {
        scoreSeverity = 'error';
    }

    return Section({
        dataSection: 'score',
        children: MetricGrid({
            children:
                MetricCard({ label: 'Score', value: String(result.score) + '%', severity: scoreSeverity }) +
                MetricCard({ label: 'Grade', value: result.grade, severity: scoreSeverity }),
        }),
    });
}

function buildBreakdown(result: ReleaseScoreResult): string {
    const items = result.breakdown
        .map((item) => {
            const statusIcon = item.status === 'pass' ? '\u2713' : '\u2717';
            const scoreText = item.noData ? 'N/A' : String(item.score);
            const statusText = item.noData ? 'no data' : item.status;
            return `<div data-component="breakdown-item" data-severity="${item.status}">
            <span data-part="label">${sanitizeHtml(item.label)}</span>
            <span data-part="score">${statusIcon} ${scoreText}</span>
            ${Badge({ variant: item.status === 'pass' ? 'pass' : 'fail', children: statusText })}
        </div>`;
        })
        .join('');

    return Section({
        dataSection: 'breakdown',
        title: 'Breakdown',
        children: `<div data-component="breakdown-list">${items}</div>`,
    });
}

function buildRecommendation(result: ReleaseScoreResult): string {
    return Section({
        dataSection: 'recommendation',
        title: 'Recommendation',
        children: `<div data-part="recommendation">${sanitizeHtml(result.recommendation)}</div>`,
    });
}
