/**
 * Release Readiness Score — HTML rendering layer.
 *
 * Receives computed ReleaseScoreResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module release-score-renderer
 */

import { buildHtmlPage } from '../report/html-factory.js';
import { buildCss } from '../report/report-styles.js';
import { sanitizeHtml } from '../escape.js';
import { Badge, MetricCard, MetricGrid, Section, RecommendedActions, EmptyState } from '../primitives/index.js';
import type { ReleaseScoreResult } from './release-score.js';
import { icon } from '../icons.js';

const SCORE_CRITICAL = 50;
const SCORE_QUALITY_GATE = 80;

export function generateReleaseScoreHtml(result: ReleaseScoreResult | null | undefined): string {
    if (!result) {
        return buildHtmlPage({
            title: 'Release Readiness Score',
            styles: buildCss(),
            theme: 'system',
            bodyContent: wrapContainer(
                'Release Readiness Score',
                EmptyState({
                    title: 'No release score data available',
                    description:
                        'Release score requires pipeline run data and quality gate results. No data was found.',
                    action: 'Run the release score analysis with valid pipeline and quality data.',
                    icon: icon('info', 48),
                }),
            ),
            footer: 'Generated by QA Tools — Release Readiness Score',
        });
    }

    const bodyContent = wrapContainer(
        'Release Readiness Score',
        buildScoreSummary(result) +
            buildBreakdown(result) +
            buildRecommendation(result) +
            buildRecommendedActions(result),
    );

    return buildHtmlPage({
        title: 'Release Readiness Score',
        styles: buildCss(),
        theme: 'system',
        bodyContent,
        footer: 'Generated by QA Tools',
    });
}

function wrapContainer(pageTitle: string, children: string): string {
    return `<div data-component="container" data-dashboard="release-score">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        <div data-part="timestamp">${sanitizeHtml(new Date().toISOString())}</div>
        ${children}
    </div>`;
}

function buildScoreSummary(result: ReleaseScoreResult): string {
    let scoreSeverity: 'success' | 'warn' | 'error';
    if (result.score >= SCORE_QUALITY_GATE) {
        scoreSeverity = 'success';
    } else if (result.score >= SCORE_CRITICAL) {
        scoreSeverity = 'warn';
    } else {
        scoreSeverity = 'error';
    }

    // Calculate deployment gate status
    const deploymentReady = result.score >= SCORE_QUALITY_GATE;
    const gateStatus = deploymentReady ? `${icon('check-circle', 14)} READY` : `${icon('x-circle', 14)} NOT READY`;
    const gateSeverity = deploymentReady ? 'success' : 'error';

    // Count passed/failed checks
    const passedChecks = result.breakdown.filter((item) => item.status === 'pass').length;
    const failedChecks = result.breakdown.filter((item) => item.status === 'fail').length;
    const totalChecks = result.breakdown.length;

    return Section({
        dataSection: 'score',
        children: MetricGrid({
            children:
                MetricCard({
                    label: 'Score',
                    value: String(result.score) + '%',
                    severity: scoreSeverity,
                    target: `target: >=${SCORE_QUALITY_GATE}%`,
                }) +
                MetricCard({ label: 'Grade', value: result.grade, severity: scoreSeverity }) +
                MetricCard({
                    label: 'Checks Passed',
                    value: `${passedChecks}/${totalChecks}`,
                    severity: failedChecks > 0 ? 'warn' : 'success',
                }) +
                MetricCard({ label: 'Release Gate', value: gateStatus, severity: gateSeverity }),
        }),
    });
}

function buildBreakdown(result: ReleaseScoreResult): string {
    const items = result.breakdown
        .map((item) => {
            const statusIcon = item.status === 'pass' ? icon('check-circle', 14) : icon('x-circle', 14);
            const scoreText = item.noData ? 'N/A' : String(item.score);
            const statusText = item.noData ? 'no data' : item.status;

            // Add threshold context
            let thresholdHint = '';
            if (item.status === 'fail' && !item.noData) {
                thresholdHint = ` (score: ${item.score}, needs improvement)`;
            } else if (item.status === 'pass' && !item.noData) {
                thresholdHint = ` (score: ${item.score})`;
            }

            return `<div data-component="breakdown-item" data-severity="${item.status}">
            <span data-part="label">${sanitizeHtml(item.label)}</span>
            <span data-part="score">${statusIcon} ${scoreText}${thresholdHint}</span>
            ${Badge({ variant: item.status === 'pass' ? 'pass' : 'fail', children: statusText })}
        </div>`;
        })
        .join('');

    return Section({
        dataSection: 'breakdown',
        title: 'Breakdown',
        children: `<div data-component="breakdown-list">${items}</div>`,
    });
}

function buildRecommendation(result: ReleaseScoreResult): string {
    return Section({
        dataSection: 'recommendation',
        title: 'Recommendation',
        children: `<div data-part="recommendation">${sanitizeHtml(result.recommendation)}</div>`,
    });
}

function buildRecommendedActions(result: ReleaseScoreResult): string {
    const actions: Array<{ severity: 'error' | 'warn' | 'info'; text: string }> = [];

    // Action 1: Low score
    if (result.score < SCORE_CRITICAL) {
        actions.push({
            severity: 'error',
            text: `Release score is ${result.score}% — critically low. Critical issues must be resolved before release. Do NOT deploy until score reaches ${SCORE_CRITICAL}%.`,
        });
    }

    // Action 2: Below quality gate
    if (result.score >= SCORE_CRITICAL && result.score < SCORE_QUALITY_GATE) {
        actions.push({
            severity: 'warn',
            text: `Release score is ${result.score}% — below the ${SCORE_QUALITY_GATE}% quality gate. Address remaining issues to reach deployment readiness.`,
        });
    }

    // Action 3: Failed checks with specific names
    const failedItems = result.breakdown.filter((item) => item.status === 'fail');
    if (failedItems.length > 0) {
        actions.push({
            severity: 'warn',
            text: `${failedItems.length} check(s) failed: ${failedItems.map((item) => sanitizeHtml(item.label)).join(', ')}. Review and fix before release.`,
        });
    }

    // Action 4: Deployment gate
    if (result.score >= SCORE_QUALITY_GATE) {
        actions.push({
            severity: 'info',
            text: 'Release score meets quality thresholds. Ready for deployment.',
        });
    }

    if (actions.length === 0) {
        actions.push({
            severity: 'info',
            text: 'Release score meets quality thresholds. Ready for deployment.',
        });
    }

    return Section({
        dataSection: 'actions',
        title: 'Recommended Actions',
        children: RecommendedActions({ actions }),
    });
}
