/**
 * Release Readiness Score — HTML rendering layer.
 *
 * Receives computed ReleaseScoreResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module release-score-renderer
 */

import { buildHtmlPage } from '../report/html-factory.js';
import { buildCss } from '../report/report-styles.js';
import { buildReleaseSection } from '../report/report-sections.js';
import { formatDateISO } from '../date-utils.js';
import type { ReleaseScoreResult } from './release-score.js';

export function generateReleaseScoreHtml(result: ReleaseScoreResult): string {
    const bodyContent =
        '<h1>Release Readiness Score</h1>' +
        buildReleaseSection(result.score, result.grade, result.breakdown, result.recommendation);
    return buildHtmlPage({
        title: 'Release Readiness Score',
        styles: buildCss(),
        theme: 'system',
        bodyContent,
        footer: `Generated by QA Tools · ${formatDateISO()}`,
    });
}
