/**
 * Silent Regression Detector — HTML rendering layer.
 *
 * Receives computed RegressionDetectionResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module silent-regression-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from '../report/html-factory.js';
import { buildCss } from '../report/report-styles.js';
import {
    MetricCard,
    MetricGrid,
    DataTable,
    Badge,
    Section,
    EmptyState,
    RecommendedActions,
} from '../primitives/index.js';
import type { TableColumn, TableRow } from '../primitives/index.js';
import { rootLogger } from '../logger.js';
import type { RegressionDetectionResult, RegressionEntry } from '../types/data-hub-extensions.js';

const REGRESSION_COUNT_TARGET = 0;
const AVG_INCREASE_WARN_THRESHOLD = 20;
const AVG_INCREASE_ERROR_THRESHOLD = 50;

function severityBadgeVariant(severity: RegressionEntry['severity']): 'fail' | 'warn' | 'info' | 'default' {
    switch (severity) {
        case 'critical':
        case 'high':
            return 'fail';
        case 'medium':
            return 'warn';
        case 'low':
            return 'info';
        default:
            return 'default';
    }
}

export function generateSilentRegressionHtml(
    result: RegressionDetectionResult | null | undefined,
    title?: string,
): string {
    try {
        if (!result) {
            rootLogger.error(
                'Silent regression result is null or undefined. Provide a valid RegressionDetectionResult.',
            );
            return buildErrorPage('Error generating report', 'Error generating silent regression report');
        }
        const pageTitle = title || 'Silent Regression Detector';

        const bodyContent = wrapContainer(
            pageTitle,
            buildMetricSummary(result) + buildRegressions(result) + buildRecommendedActions(result),
            result.timestamp,
        );

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Silent Regression Detector',
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error(
            'Failed to generate silent regression HTML: ' + msg + '. Verify buildCss and buildHtmlPage dependencies.',
        );
        return buildErrorPage('Error generating report', 'Error generating silent regression report');
    }
}

function wrapContainer(pageTitle: string, children: string, timestamp: string): string {
    return `<div data-component="container" data-dashboard="silent-regression">
        <h1>${sanitizeHtml(pageTitle)}</h1>
        <div data-part="timestamp">${sanitizeHtml(timestamp)}</div>
        ${children}
    </div>`;
}

function buildMetricSummary(result: RegressionDetectionResult): string {
    // Calculate average percentage increase across regressions
    const avgIncrease =
        result.regressions.length > 0
            ? Math.round(
                  result.regressions.reduce((sum, r) => {
                      const increase =
                          r.meanDuration > 0 ? ((r.currentDuration - r.meanDuration) / r.meanDuration) * 100 : 0;
                      return sum + increase;
                  }, 0) / result.regressions.length,
              )
            : 0;

    return Section({
        dataSection: 'summary',
        title: 'Summary',
        children: MetricGrid({
            children:
                MetricCard({ label: 'Total Tests', value: String(result.totalTests) }) +
                MetricCard({
                    label: 'Regressions Found',
                    value: String(result.regressions.length),
                    severity: result.regressions.length > 0 ? 'error' : 'success',
                    target: `target: ${REGRESSION_COUNT_TARGET}`,
                }) +
                MetricCard({
                    label: 'Avg Increase',
                    value: avgIncrease > 0 ? `+${avgIncrease}%` : '0%',
                    severity: (() => {
                        if (avgIncrease > AVG_INCREASE_ERROR_THRESHOLD) return 'error';
                        if (avgIncrease > AVG_INCREASE_WARN_THRESHOLD) return 'warn';
                        return 'default';
                    })(),
                    target: `target: <${AVG_INCREASE_WARN_THRESHOLD}%`,
                }) +
                MetricCard({ label: 'Threshold (z)', value: '>' + String(result.threshold) }),
        }),
    });
}

function buildRegressions(result: RegressionDetectionResult): string {
    if (result.regressions.length === 0) {
        return EmptyState({
            title: 'No silent regressions detected',
            description: 'All tests are within the normal duration range. No performance regressions were found.',
            action: 'Monitor test duration trends over time to detect regressions early.',
        });
    }

    // Sort by z-score (most severe first)
    const sorted = [...result.regressions].sort((a, b) => b.zScore - a.zScore);

    const columns: TableColumn[] = [
        { key: 'title', label: 'Test', width: '25%' },
        { key: 'current', label: 'Current (s)', align: 'right' },
        { key: 'mean', label: 'Mean (s)', align: 'right' },
        { key: 'increase', label: 'Increase', align: 'right' },
        { key: 'zscore', label: 'Z-Score', align: 'right' },
        { key: 'severity', label: 'Severity' },
    ];

    const rows: TableRow[] = sorted.map((r, i) => {
        // Calculate percentage increase
        const increase =
            r.meanDuration > 0 ? Math.round(((r.currentDuration - r.meanDuration) / r.meanDuration) * 100) : 0;
        const increaseStr = increase > 0 ? `+${increase}%` : '0%';

        return {
            key: String(i),
            cells: {
                title: sanitizeHtml(r.title),
                current: r.currentDuration.toFixed(3),
                mean: r.meanDuration.toFixed(3),
                increase: increaseStr,
                zscore: r.zScore.toFixed(2),
                severity: Badge({
                    variant: severityBadgeVariant(r.severity),
                    children: r.severity,
                }),
            },
        };
    });

    return Section({
        dataSection: 'regressions',
        title: 'Regression Table',
        children: DataTable({
            columns,
            rows,
            caption: `Tests with duration regression (z-score > ${result.threshold}) — sorted by severity`,
        }),
    });
}

function buildRecommendedActions(result: RegressionDetectionResult): string {
    // legitimate: zero regressions = condition-false (nothing to recommend) — absence IS the message; EmptyState would be redundant noise (Rule 25.3 intent).
    if (result.regressions.length === 0) return '';

    const criticalCount = result.regressions.filter((r) => r.severity === 'critical' || r.severity === 'high').length;
    const actions: Array<{ text: string; severity: 'error' | 'warn' | 'info' }> = [];

    if (criticalCount > 0) {
        const criticalTests = result.regressions
            .filter((r) => r.severity === 'critical' || r.severity === 'high')
            .slice(0, 3)
            .map((r) => sanitizeHtml(r.title))
            .join(', ');
        const moreText = criticalCount > 3 ? ` and ${criticalCount - 3} more` : '';
        actions.push({
            text: `${criticalCount} critical/high severity regression(s) detected: ${criticalTests}${moreText}. Investigate immediately — these tests show significant duration increases.`,
            severity: 'error',
        });
    }

    const mediumCount = result.regressions.filter((r) => r.severity === 'medium').length;
    if (mediumCount > 0) {
        actions.push({
            text: `${mediumCount} medium severity regression(s) detected. Review test infrastructure and consider optimizing test execution.`,
            severity: 'warn',
        });
    }

    // Add root cause guidance based on data patterns
    const avgStdDev =
        result.regressions.length > 0
            ? result.regressions.reduce((sum, r) => sum + r.stdDev, 0) / result.regressions.length
            : 0;

    if (avgStdDev > 1) {
        actions.push({
            text: 'High standard deviation detected — regressions may be caused by flaky tests or external service latency. Check test isolation and external dependencies.',
            severity: 'info',
        });
    } else {
        actions.push({
            text: 'Investigate root cause: check for test data growth, resource contention, or infrastructure changes.',
            severity: 'info',
        });
    }

    return Section({
        dataSection: 'actions',
        title: 'Recommended Actions',
        children: RecommendedActions({ actions }),
    });
}
