/**
 * Silent Regression Detector — HTML rendering layer.
 *
 * Receives computed RegressionResult and produces a complete HTML page.
 * This module has NO business logic — only presentation.
 *
 * @module silent-regression-renderer
 */

import { sanitizeHtml } from '../escape.js';
import { buildHtmlPage, buildErrorPage } from '../report/html-factory.js';
import { buildCss } from '../report/report-styles.js';
import { MetricCard, MetricGrid, DataTable, Badge } from '../primitives/index.js';
import type { TableColumn, TableRow } from '../primitives/index.js';
import { rootLogger } from '../logger.js';
import type { RegressionResult, RegressionEntry } from './silent-regression.js';

function severityBadgeVariant(severity: RegressionEntry['severity']): 'fail' | 'warn' | 'info' | 'default' {
    switch (severity) {
        case 'critical':
        case 'high':
            return 'fail';
        case 'medium':
            return 'warn';
        case 'low':
            return 'info';
        default:
            return 'default';
    }
}

export function generateSilentRegressionHtml(result: RegressionResult | null | undefined, title?: string): string {
    try {
        if (!result) {
            rootLogger.error('Silent regression result is null or undefined. Provide a valid RegressionResult.');
            return buildErrorPage('Error generating report', 'Error generating silent regression report');
        }
        const pageTitle = title || 'Silent Regression Detector';

        const summaryCards = MetricGrid({
            children:
                MetricCard({ label: 'Total Tests', value: String(result.totalTests) }) +
                MetricCard({
                    label: 'Regressions Found',
                    value: String(result.regressions.length),
                    severity: result.regressions.length > 0 ? 'error' : 'success',
                }) +
                MetricCard({ label: 'Threshold (z)', value: '>' + String(result.threshold) }),
        });

        let tableHtml: string;
        if (result.regressions.length === 0) {
            tableHtml =
                '<p style="color:var(--color-success);font-weight:600">No silent regressions detected. All tests are within the normal duration range.</p>';
        } else {
            const columns: TableColumn[] = [
                { key: 'title', label: 'Test', width: '30%' },
                { key: 'current', label: 'Current (s)', align: 'right' },
                { key: 'mean', label: 'Mean (s)', align: 'right' },
                { key: 'stddev', label: 'Std Dev', align: 'right' },
                { key: 'zscore', label: 'Z-Score', align: 'right' },
                { key: 'severity', label: 'Severity' },
            ];

            const rows: TableRow[] = result.regressions.map((r, i) => ({
                key: String(i),
                cells: {
                    title: sanitizeHtml(r.title),
                    current: r.currentDuration.toFixed(3),
                    mean: r.meanDuration.toFixed(3),
                    stddev: r.stdDev.toFixed(3),
                    zscore: r.zScore.toFixed(2),
                    severity: Badge({
                        variant: severityBadgeVariant(r.severity),
                        children: r.severity,
                    }),
                },
            }));

            tableHtml = DataTable({ columns, rows });
        }

        const bodyContent = '<h1>' + sanitizeHtml(pageTitle) + '</h1>' + summaryCards + tableHtml;

        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Silent Regression Detector',
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error(
            'Failed to generate silent regression HTML: ' + msg + '. Verify buildCss and buildHtmlPage dependencies.',
        );
        return buildErrorPage('Error generating report', 'Error generating silent regression report');
    }
}
