export interface ConfigField {
    key: string;
    envVar: string;
    type: 'string' | 'boolean' | 'number';
    defaultVal?: string | number | boolean;
    description: string;
}

export const CONFIG_SCHEMA: ConfigField[] = [
    { key: 'jiraBaseUrl', envVar: 'JIRA_BASE_URL', type: 'string', description: 'Jira base URL' },
    { key: 'jiraPersonalToken', envVar: 'JIRA_PERSONAL_TOKEN', type: 'string', description: 'Jira personal token' },
    { key: 'xrayBaseUrl', envVar: 'XRAY_BASE_URL', type: 'string', description: 'Xray base URL' },
    {
        key: 'xrayMode',
        envVar: 'XRAY_MODE',
        type: 'string',
        defaultVal: 'server',
        description: 'Xray mode (server|cloud)',
    },
    { key: 'xrayClientId', envVar: 'XRAY_CLIENT_ID', type: 'string', description: 'Xray client ID' },
    { key: 'xrayClientSecret', envVar: 'XRAY_CLIENT_SECRET', type: 'string', description: 'Xray client secret' },
    {
        key: 'xrayCloudUrl',
        envVar: 'XRAY_CLOUD_URL',
        type: 'string',
        defaultVal: 'https://xray.cloud.getxray.app',
        description: 'Xray cloud URL',
    },
    {
        key: 'jiraProject',
        envVar: 'JIRA_PROJECT',
        type: 'string',
        defaultVal: 'YOUR_PROJECT_KEY',
        description: 'Jira project key',
    },
    { key: 'gitToken', envVar: 'GIT_TOKEN', type: 'string', description: 'Git token' },
    { key: 'gitBaseUrl', envVar: 'GIT_BASE_URL', type: 'string', description: 'Git base URL' },
    { key: 'githubToken', envVar: 'GITHUB_TOKEN', type: 'string', description: 'GitHub token' },
    {
        key: 'githubApiUrl',
        envVar: 'GITHUB_API_URL',
        type: 'string',
        defaultVal: 'https://api.github.com',
        description: 'GitHub API URL',
    },
    { key: 'cypressProjectPath', envVar: 'CYPRESS_PROJECT_PATH', type: 'string', description: 'Cypress project path' },
    { key: 'csvDefaultPath', envVar: 'CSV_DEFAULT_PATH', type: 'string', description: 'CSV default path' },
    { key: 'autoChoice', envVar: 'AUTO_CHOICE', type: 'string', description: 'Auto choice' },
    {
        key: 'autoConfirm',
        envVar: 'AUTO_CONFIRM',
        type: 'boolean',
        defaultVal: false,
        description: 'Auto confirm mode',
    },
    { key: 'dryRun', envVar: 'DRY_RUN', type: 'boolean', defaultVal: false, description: 'Dry run mode' },
    { key: 'debug', envVar: 'DEBUG', type: 'boolean', defaultVal: false, description: 'Debug mode' },
    { key: 'quiet', envVar: 'QUIET', type: 'boolean', defaultVal: false, description: 'Quiet mode' },
    {
        key: 'onError',
        envVar: 'ON_ERROR',
        type: 'string',
        defaultVal: 'abort',
        description: 'Error action (abort|skip|continue)',
    },
    { key: 'csvPath', envVar: 'CSV_PATH', type: 'string', description: 'CSV path' },
    { key: 'csvLabels', envVar: 'CSV_LABELS', type: 'string', description: 'CSV labels' },
    { key: 'jsonPath', envVar: 'JSON_PATH', type: 'string', description: 'JSON path' },
    { key: 'jsonLabels', envVar: 'JSON_LABELS', type: 'string', description: 'JSON labels' },
    { key: 'logLevel', envVar: 'LOG_LEVEL', type: 'string', defaultVal: 'INFO', description: 'Log level' },
    { key: 'logFile', envVar: 'LOG_FILE', type: 'boolean', defaultVal: false, description: 'Log to file' },
    { key: 'logDir', envVar: 'LOG_DIR', type: 'string', defaultVal: 'logs', description: 'Log directory' },
    {
        key: 'logMaxSize',
        envVar: 'LOG_MAX_SIZE',
        type: 'number',
        defaultVal: 5242880,
        description: 'Max log file size',
    },
    { key: 'xdgStateHome', envVar: 'XDG_STATE_HOME', type: 'string', description: 'XDG state home' },
    { key: 'llmApiKey', envVar: 'LLM_API_KEY', type: 'string', description: 'LLM API key' },
    {
        key: 'llmModel',
        envVar: 'LLM_MODEL',
        type: 'string',
        defaultVal: 'google/gemini-2.0-flash-exp',
        description: 'LLM model',
    },
    {
        key: 'llmBaseUrl',
        envVar: 'LLM_BASE_URL',
        type: 'string',
        defaultVal: 'https://openrouter.ai/api/v1',
        description: 'LLM base URL',
    },
    { key: 'llmSmallApiKey', envVar: 'LLM_SMALL_API_KEY', type: 'string', description: 'LLM small API key' },
    {
        key: 'llmSmallModel',
        envVar: 'LLM_SMALL_MODEL',
        type: 'string',
        defaultVal: 'gemini-2.0-flash-lite',
        description: 'LLM small model',
    },
    { key: 'llmFastApiKey', envVar: 'LLM_FAST_API_KEY', type: 'string', description: 'LLM fast API key' },
    {
        key: 'llmFastModel',
        envVar: 'LLM_FAST_MODEL',
        type: 'string',
        defaultVal: 'llama-3.1-8b-instant',
        description: 'LLM fast model',
    },
    {
        key: 'llmFastBaseUrl',
        envVar: 'LLM_FAST_BASE_URL',
        type: 'string',
        defaultVal: 'https://api.groq.com/openai/v1',
        description: 'LLM fast base URL',
    },
    { key: 'llmReviewApiKey', envVar: 'LLM_REVIEW_API_KEY', type: 'string', description: 'LLM review API key' },
    {
        key: 'llmReviewModel',
        envVar: 'LLM_REVIEW_MODEL',
        type: 'string',
        defaultVal: 'gemini-2.0-flash-exp',
        description: 'LLM review model',
    },
    {
        key: 'llmReviewBaseUrl',
        envVar: 'LLM_REVIEW_BASE_URL',
        type: 'string',
        defaultVal: 'https://generativelanguage.googleapis.com/v1beta',
        description: 'LLM review base URL',
    },
    { key: 'llmFallbackApiKey', envVar: 'LLM_FALLBACK_API_KEY', type: 'string', description: 'LLM fallback API key' },
    {
        key: 'llmFallbackModel',
        envVar: 'LLM_FALLBACK_MODEL',
        type: 'string',
        defaultVal: 'meta/llama3-70b-instruct',
        description: 'LLM fallback model',
    },
    {
        key: 'llmFallbackBaseUrl',
        envVar: 'LLM_FALLBACK_BASE_URL',
        type: 'string',
        defaultVal: 'https://integrate.api.nvidia.com/v1',
        description: 'LLM fallback base URL',
    },
    { key: 'llmBatchApiKey', envVar: 'LLM_BATCH_API_KEY', type: 'string', description: 'LLM batch API key' },
    {
        key: 'llmBatchModel',
        envVar: 'LLM_BATCH_MODEL',
        type: 'string',
        defaultVal: 'gpt-4o-mini',
        description: 'LLM batch model',
    },
    {
        key: 'llmBatchBaseUrl',
        envVar: 'LLM_BATCH_BASE_URL',
        type: 'string',
        defaultVal: 'https://models.inference.ai.azure.com',
        description: 'LLM batch base URL',
    },
    {
        key: 'llmMaxTokens',
        envVar: 'LLM_MAX_TOKENS_PER_OP',
        type: 'number',
        defaultVal: 128000,
        description: 'LLM max tokens per operation',
    },
    {
        key: 'llmMaxTotalTokens',
        envVar: 'LLM_MAX_TOTAL_TOKENS',
        type: 'number',
        defaultVal: 0,
        description: 'LLM max total tokens',
    },
    {
        key: 'knownIssuesPath',
        envVar: 'KNOWN_ISSUES_PATH',
        type: 'string',
        defaultVal: '',
        description: 'Known issues JSON path',
    },
];
