interface ConfigFieldBase {
    key: string;
    envVar: string;
    description: string;
    category?: string;
    allowedValues?: string[];
}

export interface ConfigFieldString extends ConfigFieldBase {
    type: 'string';
    defaultVal?: string;
}

export interface ConfigFieldBoolean extends ConfigFieldBase {
    type: 'boolean';
    defaultVal?: boolean;
}

export interface ConfigFieldNumber extends ConfigFieldBase {
    type: 'number';
    defaultVal?: number;
}

export type ConfigField = ConfigFieldString | ConfigFieldBoolean | ConfigFieldNumber;

export const CONFIG_SCHEMA: ConfigField[] = [
    { key: 'jiraBaseUrl', envVar: 'JIRA_BASE_URL', type: 'string', category: 'jira', description: 'Jira base URL' },
    {
        key: 'jiraPersonalToken',
        envVar: 'JIRA_PERSONAL_TOKEN',
        type: 'string',
        category: 'jira',
        description: 'Jira personal token (PAT para server, apiToken para cloud)',
    },
    {
        key: 'jiraUserEmail',
        envVar: 'JIRA_USER_EMAIL',
        type: 'string',
        category: 'jira',
        description:
            'Jira user email (cloud only) — combined with JIRA_PERSONAL_TOKEN as email:apiToken for Basic auth',
    },
    {
        key: 'jiraMode',
        envVar: 'JIRA_MODE',
        type: 'string',
        defaultVal: 'server',
        category: 'jira',
        allowedValues: ['server', 'cloud'],
        description: 'Jira mode (server|cloud)',
    },
    {
        key: 'proxyUrl',
        envVar: 'QA_PROXY_URL',
        type: 'string',
        category: 'jira',
        description:
            'Egress proxy URL (e.g. http://127.0.0.1:9000 for Zscaler). Falls back to HTTPS_PROXY/HTTP_PROXY env',
    },
    { key: 'xrayBaseUrl', envVar: 'XRAY_BASE_URL', type: 'string', category: 'jira', description: 'Xray base URL' },
    {
        key: 'xrayMode',
        envVar: 'XRAY_MODE',
        type: 'string',
        defaultVal: 'server',
        category: 'jira',
        allowedValues: ['server', 'cloud'],
        description: 'Xray mode (server|cloud)',
    },
    { key: 'xrayClientId', envVar: 'XRAY_CLIENT_ID', type: 'string', category: 'jira', description: 'Xray client ID' },
    {
        key: 'xrayClientSecret',
        envVar: 'XRAY_CLIENT_SECRET',
        type: 'string',
        category: 'jira',
        description: 'Xray client secret',
    },
    {
        key: 'xrayCloudUrl',
        envVar: 'XRAY_CLOUD_URL',
        type: 'string',
        category: 'jira',
        defaultVal: 'https://xray.cloud.getxray.app',
        description: 'Xray cloud URL',
    },
    {
        key: 'jiraProject',
        envVar: 'JIRA_PROJECT',
        type: 'string',
        category: 'jira',
        defaultVal: 'YOUR_PROJECT_KEY',
        description: 'Jira project key',
    },
    { key: 'gitToken', envVar: 'GIT_TOKEN', type: 'string', category: 'git', description: 'Git token' },
    { key: 'gitBaseUrl', envVar: 'GIT_BASE_URL', type: 'string', category: 'git', description: 'Git base URL' },
    { key: 'githubToken', envVar: 'GITHUB_TOKEN', type: 'string', category: 'github', description: 'GitHub token' },
    {
        key: 'githubApiUrl',
        envVar: 'GITHUB_API_URL',
        type: 'string',
        category: 'github',
        defaultVal: 'https://api.github.com',
        description: 'GitHub API URL',
    },
    {
        key: 'cypressProjectPath',
        envVar: 'CYPRESS_PROJECT_PATH',
        type: 'string',
        category: 'cypress',
        description: 'Cypress project path',
    },
    {
        key: 'csvDefaultPath',
        envVar: 'CSV_DEFAULT_PATH',
        type: 'string',
        category: 'import',
        description: 'CSV default path',
    },
    { key: 'autoChoice', envVar: 'AUTO_CHOICE', type: 'string', category: 'behavior', description: 'Auto choice' },
    {
        key: 'autoConfirm',
        envVar: 'AUTO_CONFIRM',
        type: 'boolean',
        category: 'behavior',
        defaultVal: false,
        description: 'Auto confirm mode',
    },
    {
        key: 'dryRun',
        envVar: 'DRY_RUN',
        type: 'boolean',
        category: 'behavior',
        defaultVal: false,
        description: 'Dry run mode',
    },
    {
        key: 'debug',
        envVar: 'DEBUG',
        type: 'boolean',
        category: 'behavior',
        defaultVal: false,
        description: 'Debug mode',
    },
    {
        key: 'quiet',
        envVar: 'QUIET',
        type: 'boolean',
        category: 'behavior',
        defaultVal: false,
        description: 'Quiet mode',
    },
    {
        key: 'onError',
        envVar: 'ON_ERROR',
        type: 'string',
        category: 'behavior',
        defaultVal: 'abort',
        allowedValues: ['abort', 'skip', 'continue'],
        description: 'Error action (abort|skip|continue)',
    },
    { key: 'csvPath', envVar: 'CSV_PATH', type: 'string', category: 'import', description: 'CSV path' },
    { key: 'csvLabels', envVar: 'CSV_LABELS', type: 'string', category: 'import', description: 'CSV labels' },
    { key: 'jsonPath', envVar: 'JSON_PATH', type: 'string', category: 'import', description: 'JSON path' },
    { key: 'jsonLabels', envVar: 'JSON_LABELS', type: 'string', category: 'import', description: 'JSON labels' },
    {
        key: 'logLevel',
        envVar: 'LOG_LEVEL',
        type: 'string',
        category: 'logging',
        defaultVal: 'INFO',
        allowedValues: ['TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR'],
        description: 'Log level',
    },
    {
        key: 'logFile',
        envVar: 'LOG_FILE',
        type: 'boolean',
        category: 'logging',
        defaultVal: false,
        description: 'Log to file',
    },
    {
        key: 'logDir',
        envVar: 'LOG_DIR',
        type: 'string',
        category: 'logging',
        defaultVal: 'logs',
        description: 'Log directory',
    },
    {
        key: 'logMaxSize',
        envVar: 'LOG_MAX_SIZE',
        type: 'number',
        category: 'logging',
        defaultVal: 5242880,
        description: 'Max log file size',
    },
    { key: 'xdgStateHome', envVar: 'XDG_STATE_HOME', type: 'string', category: 'state', description: 'XDG state home' },
    {
        key: 'llmProvider',
        envVar: 'LLM_PROVIDER',
        type: 'string',
        category: 'llm',
        defaultVal: '',
        allowedValues: [
            '',
            'opencode-go',
            'opencode-zen',
            'openrouter',
            'openai',
            'anthropic',
            'gemini',
            'groq',
            'github-models',
            'nvidia-nim',
            'custom',
        ],
        description: 'LLM primary provider (auto-detect if empty)',
    },
    {
        key: 'llmFallbackProvider',
        envVar: 'LLM_FALLBACK_PROVIDER',
        type: 'string',
        category: 'llm',
        defaultVal: '',
        allowedValues: [
            '',
            'opencode-go',
            'opencode-zen',
            'openrouter',
            'openai',
            'anthropic',
            'gemini',
            'groq',
            'github-models',
            'nvidia-nim',
            'custom',
        ],
        description: 'LLM fallback provider (optional)',
    },
    { key: 'llmApiKey', envVar: 'LLM_API_KEY', type: 'string', category: 'llm', description: 'LLM API key' },
    {
        key: 'llmModel',
        envVar: 'LLM_MODEL',
        type: 'string',
        category: 'llm',
        defaultVal: 'google/gemini-2.0-flash-exp',
        description: 'LLM model',
    },
    {
        key: 'llmBaseUrl',
        envVar: 'LLM_BASE_URL',
        type: 'string',
        category: 'llm',
        defaultVal: 'https://openrouter.ai/api/v1',
        description: 'LLM base URL',
    },
    {
        key: 'llmFastApiKey',
        envVar: 'LLM_FAST_API_KEY',
        type: 'string',
        category: 'llm',
        description: 'LLM fast API key',
    },
    {
        key: 'llmFastModel',
        envVar: 'LLM_FAST_MODEL',
        type: 'string',
        category: 'llm',
        defaultVal: 'llama-3.1-8b-instant',
        description: 'LLM fast model',
    },
    {
        key: 'llmFastBaseUrl',
        envVar: 'LLM_FAST_BASE_URL',
        type: 'string',
        category: 'llm',
        defaultVal: 'https://api.groq.com/openai/v1',
        description: 'LLM fast base URL',
    },
    {
        key: 'llmReviewApiKey',
        envVar: 'LLM_REVIEW_API_KEY',
        type: 'string',
        category: 'llm',
        description: 'LLM review API key',
    },
    {
        key: 'llmReviewModel',
        envVar: 'LLM_REVIEW_MODEL',
        type: 'string',
        category: 'llm',
        defaultVal: 'gemini-2.0-flash-exp',
        description: 'LLM review model',
    },
    {
        key: 'llmReviewBaseUrl',
        envVar: 'LLM_REVIEW_BASE_URL',
        type: 'string',
        category: 'llm',
        defaultVal: 'https://generativelanguage.googleapis.com/v1beta',
        description: 'LLM review base URL',
    },
    {
        key: 'llmFallbackApiKey',
        envVar: 'LLM_FALLBACK_API_KEY',
        type: 'string',
        category: 'llm',
        description: 'LLM fallback API key',
    },
    {
        key: 'llmFallbackModel',
        envVar: 'LLM_FALLBACK_MODEL',
        type: 'string',
        category: 'llm',
        defaultVal: 'meta/llama3-70b-instruct',
        description: 'LLM fallback model',
    },
    {
        key: 'llmFallbackBaseUrl',
        envVar: 'LLM_FALLBACK_BASE_URL',
        type: 'string',
        category: 'llm',
        defaultVal: 'https://integrate.api.nvidia.com/v1',
        description: 'LLM fallback base URL',
    },
    {
        key: 'llmBatchApiKey',
        envVar: 'LLM_BATCH_API_KEY',
        type: 'string',
        category: 'llm',
        description: 'LLM batch API key (same as GITHUB_TOKEN)',
    },
    {
        key: 'llmBatchModel',
        envVar: 'LLM_BATCH_MODEL',
        type: 'string',
        category: 'llm',
        defaultVal: 'gpt-4o-mini',
        description: 'LLM batch model',
    },
    {
        key: 'llmBatchBaseUrl',
        envVar: 'LLM_BATCH_BASE_URL',
        type: 'string',
        category: 'llm',
        defaultVal: 'https://models.inference.ai.azure.com',
        description: 'LLM batch base URL',
    },
    {
        key: 'llmMaxTokens',
        envVar: 'LLM_MAX_TOKENS_PER_OP',
        type: 'number',
        category: 'llm',
        defaultVal: 128000,
        description: 'LLM max tokens per operation',
    },
    {
        key: 'llmMaxTotalTokens',
        envVar: 'LLM_MAX_TOTAL_TOKENS',
        type: 'number',
        category: 'llm',
        defaultVal: 0,
        description: 'LLM max total tokens',
    },

    {
        key: 'llmReviewBudget',
        envVar: 'LLM_REVIEW_BUDGET',
        type: 'number',
        category: 'llm',
        defaultVal: 0.5,
        description: 'Maximum USD per session for adversarial review',
    },
    {
        key: 'llmReviewStrategy',
        envVar: 'LLM_REVIEW_STRATEGY',
        type: 'string',
        category: 'llm',
        defaultVal: 'selective',
        allowedValues: ['selective', 'always'],
        description: 'Review strategy (selective|always)',
    },
    {
        key: 'llmRateLimit',
        envVar: 'LLM_RATE_LIMIT',
        type: 'number',
        category: 'llm',
        defaultVal: 10,
        description: 'LLM rate limit (req/min per tier)',
    },
    {
        key: 'llmFetchRetries',
        envVar: 'LLM_FETCH_RETRIES',
        type: 'number',
        category: 'llm',
        defaultVal: 3,
        description: 'LLM fetch retries per provider',
    },
    {
        key: 'llmDiskCacheDir',
        envVar: 'LLM_DISK_CACHE_DIR',
        type: 'string',
        category: 'llm',
        defaultVal: '',
        description: 'LLM disk cache directory',
    },
    {
        key: 'llmCacheKey',
        envVar: 'LLM_CACHE_KEY',
        type: 'string',
        category: 'llm',
        defaultVal: '',
        description: 'LLM cache key override',
    },
    {
        key: 'llmDiscoveryMode',
        envVar: 'LLM_DISCOVERY_MODE',
        type: 'string',
        category: 'llm',
        defaultVal: 'static',
        allowedValues: ['static', 'auto'],
        description: 'Model discovery mode (static=registry only, auto=probe API for updates)',
    },
    {
        key: 'llmDiscoveryCacheTtl',
        envVar: 'LLM_DISCOVERY_CACHE_TTL',
        type: 'number',
        category: 'llm',
        defaultVal: 168,
        description: 'Model discovery cache TTL in hours (default: 1 week)',
    },
    {
        key: 'qaToolsLogsDir',
        envVar: 'QA_TOOLS_LOGS_DIR',
        type: 'string',
        category: 'qa-tools',
        defaultVal: 'logs',
        description: 'Log output directory',
    },
    {
        key: 'qaToolsTempDir',
        envVar: 'QA_TOOLS_TEMP_DIR',
        type: 'string',
        category: 'qa-tools',
        defaultVal: '',
        description: 'Temporary directory override',
    },
    {
        key: 'qaToolsReportsDir',
        envVar: 'QA_TOOLS_REPORTS_DIR',
        type: 'string',
        category: 'qa-tools',
        defaultVal: '',
        description: 'Reports output directory',
    },
    {
        key: 'qaAutoBug',
        envVar: 'QA_AUTO_BUG',
        type: 'boolean',
        category: 'qa-tools',
        defaultVal: false,
        description: 'Auto-create Jira bug on new failures',
    },
    {
        key: 'qaFailOn',
        envVar: 'QA_FAIL_ON',
        type: 'number',
        category: 'qa-tools',
        defaultVal: 80,
        description: 'Quality gate: minimum pass rate',
    },
    {
        key: 'githubPrNumber',
        envVar: 'GITHUB_PR_NUMBER',
        type: 'number',
        category: 'github',
        defaultVal: 0,
        description: 'GitHub PR number for comment posting',
    },
    {
        key: 'qaPublish',
        envVar: 'QA_PUBLISH',
        type: 'string',
        category: 'qa-tools',
        defaultVal: '',
        allowedValues: ['', 's3', 'gh-pages'],
        description: 'Report publish target (s3|gh-pages)',
    },
    {
        key: 'qaMappingPath',
        envVar: 'QA_MAPPING_PATH',
        type: 'string',
        category: 'qa-tools',
        defaultVal: '',
        description: 'Test-to-Jira mapping file path',
    },
    {
        key: 'benchmark',
        envVar: 'BENCHMARK',
        type: 'boolean',
        category: 'qa-tools',
        defaultVal: false,
        description: 'Enable LLM benchmark mode',
    },
    {
        key: 'qaCostPerComputeMinute',
        envVar: 'QA_COST_PER_COMPUTE_MINUTE',
        type: 'number',
        category: 'qa-tools',
        defaultVal: 0,
        description: 'Pipeline compute cost per minute (USD)',
    },
    {
        key: 'awsS3Bucket',
        envVar: 'AWS_S3_BUCKET',
        type: 'string',
        category: 'qa-tools',
        defaultVal: '',
        description: 'AWS S3 bucket for report publishing',
    },
    {
        key: 'qaGateMinPassRate',
        envVar: 'QA_GATE_MIN_PASS_RATE',
        type: 'number',
        category: 'qa-tools',
        defaultVal: 80,
        description: 'Quality gate: minimum pass rate (%)',
    },
    {
        key: 'qaGateMaxFlakyPct',
        envVar: 'QA_GATE_MAX_FLAKY_PCT',
        type: 'number',
        category: 'qa-tools',
        defaultVal: 30,
        description: 'Quality gate: maximum flaky rate (%)',
    },
    {
        key: 'qaGateMinCoverage',
        envVar: 'QA_GATE_MIN_COVERAGE',
        type: 'number',
        category: 'qa-tools',
        defaultVal: 70,
        description: 'Quality gate: minimum coverage (%)',
    },
    {
        key: 'qaGateMaxSuiteSpeed',
        envVar: 'QA_GATE_MAX_SUITE_SPEED',
        type: 'number',
        category: 'qa-tools',
        defaultVal: 8,
        description: 'Quality gate: maximum suite speed (s/test)',
    },
    {
        key: 'qaGitBlameIgnore',
        envVar: 'QA_GIT_BLAME_IGNORE',
        type: 'string',
        category: 'qa-tools',
        defaultVal: '',
        description: 'Git blame ignore revisions (space-separated hashes)',
    },
    {
        key: 'ci',
        envVar: 'CI',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'CI/CD environment flag (set by CI systems)',
    },
    {
        key: 'githubRepository',
        envVar: 'GITHUB_REPOSITORY',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'GitHub repository (owner/repo)',
    },
    {
        key: 'ciJobName',
        envVar: 'CI_JOB_NAME',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'CI job name (GitLab)',
    },
    {
        key: 'githubWorkflow',
        envVar: 'GITHUB_WORKFLOW',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'GitHub Actions workflow name',
    },
    {
        key: 'ciJobUrl',
        envVar: 'CI_JOB_URL',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'CI job URL (GitLab)',
    },
    {
        key: 'githubServerUrl',
        envVar: 'GITHUB_SERVER_URL',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'GitHub server URL',
    },
    {
        key: 'ciCommitBranch',
        envVar: 'CI_COMMIT_BRANCH',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'CI commit branch (GitLab)',
    },
    {
        key: 'githubRefName',
        envVar: 'GITHUB_REF_NAME',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'GitHub ref name',
    },
    {
        key: 'ciJobToken',
        envVar: 'CI_JOB_TOKEN',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'CI job token (GitLab)',
    },
    {
        key: 'ciProjectId',
        envVar: 'CI_PROJECT_ID',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'CI project ID (GitLab)',
    },
    {
        key: 'ciServerUrl',
        envVar: 'CI_SERVER_URL',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'CI server URL (GitLab)',
    },
    {
        key: 'ciPrNumber',
        envVar: 'CI_PR_NUMBER',
        type: 'string',
        category: 'ci',
        defaultVal: '',
        description: 'CI PR/MR number (GitLab)',
    },
    {
        key: 'skipFirstRun',
        envVar: 'SKIP_FIRST_RUN',
        type: 'boolean',
        category: 'behavior',
        defaultVal: false,
        description: 'Skip first-run wizard',
    },
    {
        key: 'noColor',
        envVar: 'NO_COLOR',
        type: 'boolean',
        category: 'behavior',
        defaultVal: false,
        description: 'Disable ANSI color output (NO_COLOR standard)',
    },
    {
        key: 'qaToolsNoClear',
        envVar: 'QA_TOOLS_NO_CLEAR',
        type: 'boolean',
        category: 'behavior',
        defaultVal: false,
        description: 'Disable console.clear() between screens',
    },
    {
        key: 'metricsMaxRuns',
        envVar: 'METRICS_MAX_RUNS',
        type: 'number',
        category: 'qa-tools',
        defaultVal: 50,
        description: 'Max metrics runs retained (prune oldest on save)',
    },
    {
        key: 'reportCacheMax',
        envVar: 'REPORT_CACHE_MAX',
        type: 'number',
        category: 'qa-tools',
        defaultVal: 20,
        description: 'Max cached CTRF reports retained (prune oldest on save)',
    },
    {
        key: 'opencodeDbTimeoutMs',
        envVar: 'OPENCODE_DB_TIMEOUT_MS',
        type: 'number',
        category: 'opencode',
        defaultVal: 300_000,
        description: 'Timeout (ms) for opencode SQLite database maintenance CLI calls',
    },
];
