/**
 * HTML flakiness dashboard generator — renders summary cards and a table with inline bars
 * for tests exceeding the flakiness threshold.
 *
 * Uses primitives and design tokens for consistent visual output.
 *
 * @module flakiness-dashboard
 */

import type { FlakinessEntry } from './metrics.js';
import { rootLogger } from './logger.js';
import { sanitizeHtml } from './escape.js';
import { buildHtmlPage, buildErrorPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { MetricCard, MetricGrid, Badge, Sparkline } from './primitives/index.js';

const THRESHOLD_PCT = 30;

/** Filter flaky entries whose rate exceeds a percentage threshold. */
export function filterHighFlakiness(flaky: FlakinessEntry[], thresholdPct = THRESHOLD_PCT): FlakinessEntry[] {
    return flaky.filter((f) => f.rate * 100 >= thresholdPct);
}

function buildFlakinessSummary(high: FlakinessEntry[], flaky: FlakinessEntry[]): string {
    return MetricGrid({
        children:
            MetricCard({
                label: 'Total Flaky Tests',
                value: String(high.length),
                severity: high.length > 5 ? 'error' : 'warn',
            }) +
            MetricCard({ label: 'Threshold', value: '>' + THRESHOLD_PCT + '%' }) +
            MetricCard({ label: 'All Candidates', value: String(flaky.length) }),
    });
}

function buildFlakinessTable(high: FlakinessEntry[]): string {
    if (high.length === 0) return '<p>No tests exceed the ' + THRESHOLD_PCT + '% flakiness threshold.</p>';
    let html =
        '<div style="overflow-x:auto;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.1)"><table style="width:100%;border-collapse:collapse;background:var(--color-surface-card);font-size:0.875rem;color:var(--color-text-primary)">' +
        '<thead style="background:var(--color-surface-elevated)"><tr>' +
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Test</th>' +
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Pass</th>' +
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Fail</th>' +
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Skip</th>' +
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Rate</th>' +
        '<th style="padding:10px 12px;font-size:0.75rem;text-transform:uppercase;color:var(--color-text-secondary);text-align:left">Bar</th>' +
        '</tr></thead><tbody>';
    for (const f of high) {
        const pct = Math.round(f.rate * 100);
        const severity = pct >= 50 ? 'high' : 'medium';
        const rowStyle =
            'border-bottom:1px solid var(--color-border-subtle);transition:background 0.15s" onmouseover="this.style.background=\'var(--color-surface-elevated)\'" onmouseout="this.style.background=\'\'">';
        html += '<tr style="' + rowStyle;
        html += '<td style="padding:8px 12px">' + sanitizeHtml(f.title.slice(0, 80)) + '</td>';
        html += '<td style="padding:8px 12px">' + f.passCount + '</td>';
        html += '<td style="padding:8px 12px">' + f.failCount + '</td>';
        html += '<td style="padding:8px 12px">' + f.skipCount + '</td>';
        html +=
            '<td style="padding:8px 12px">' +
            Badge({
                variant: severity === 'high' ? 'fail' : 'warn',
                children: pct + '%',
            }) +
            '</td>';
        html +=
            '<td style="padding:8px 12px">' +
            Sparkline({
                value: pct,
                maxValue: 100,
                width: 100,
                height: 8,
            }) +
            '</td>';
        html += '</tr>';
    }
    html += '</tbody></table></div>';
    return html;
}

/** Generate a complete HTML page with flakiness summary cards and a test table. */
export function generateFlakinessHtml(flaky: FlakinessEntry[], title?: string): string {
    try {
        const high = filterHighFlakiness(flaky);
        const pageTitle = title || 'Flakiness Dashboard';
        const bodyContent =
            '<h1>' + sanitizeHtml(pageTitle) + '</h1>' + buildFlakinessSummary(high, flaky) + buildFlakinessTable(high);
        return buildHtmlPage({
            title: pageTitle,
            styles: buildCss(),
            theme: 'system',
            bodyContent,
            footer: 'Generated by QA Tools — Flakiness Dashboard',
        });
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        rootLogger.error('Failed to generate flakiness dashboard: ' + msg);
        return buildErrorPage('Error generating dashboard', 'Error generating dashboard');
    }
}
