import { buildHtmlPage, buildThemeScript, buildErrorPage } from './html-factory.js';
import { sanitizeHtml } from './escape.js';

describe('BuildHtmlPage', () => {
    const defaults = {
        title: 'Test Report',
        styles: 'body { color: red; }',
        bodyContent: '<p>Hello</p>',
    };

    it('renders DOCTYPE + html + head + body structure', () => {
        const html = buildHtmlPage(defaults);

        expect(html).toContain('<!DOCTYPE html>');
        expect(html).toContain('<html lang="en">');
        expect(html).toContain('<head>');
        expect(html).toContain('</head>');
        expect(html).toContain('<body>');
        expect(html).toContain('</body>');
        expect(html).toContain('</html>');
    });

    it('sanitizes title', () => {
        const html = buildHtmlPage({ ...defaults, title: '<script>alert(1)</script>' });

        expect(html).toContain(sanitizeHtml('<script>alert(1)</script>'));
        expect(html).not.toContain('<script>alert(1)</script>');
    });

    it('includes lang attribute (default en)', () => {
        const html = buildHtmlPage(defaults);

        expect(html).toContain('<html lang="en">');
    });

    it('respects custom lang', () => {
        const html = buildHtmlPage({ ...defaults, lang: 'pt-BR' });

        expect(html).toContain('<html lang="pt-BR">');
    });

    it('includes theme script when theme is set', () => {
        const html = buildHtmlPage({ ...defaults, theme: 'dark' });

        expect(html).toContain('id="qa-report-theme"');
        expect(html).toContain('localStorage.setItem(');
    });

    it('omits theme script when theme is null', () => {
        const html = buildHtmlPage({ ...defaults, theme: null });

        expect(html).not.toContain('qa-report-theme');
    });

    it('includes footer wrapped in div.footer', () => {
        const html = buildHtmlPage({ ...defaults, footer: 'Generated by QA' });

        expect(html).toContain('<div class="footer">Generated by QA</div>');
    });

    it('places bodyStart before bodyContent', () => {
        const html = buildHtmlPage({ ...defaults, bodyStart: '<nav>Nav</nav>' });
        const bodyStartIdx = html.indexOf('<nav>Nav</nav>');
        const contentIdx = html.indexOf('<p>Hello</p>');

        expect(bodyStartIdx).toBeGreaterThan(0);
        expect(contentIdx).toBeGreaterThan(bodyStartIdx);
    });

    it('places bodyEnd after bodyContent', () => {
        const html = buildHtmlPage({ ...defaults, bodyEnd: '<script>init()</script>' });
        const contentIdx = html.indexOf('<p>Hello</p>');
        const bodyEndIdx = html.indexOf('<script>init()</script>');

        expect(contentIdx).toBeGreaterThan(0);
        expect(bodyEndIdx).toBeGreaterThan(contentIdx);
    });

    it('includes headExtra in head', () => {
        const html = buildHtmlPage({ ...defaults, headExtra: '<meta name="foo" content="bar">' });

        expect(html).toContain('<meta name="foo" content="bar">');

        const headEnd = html.indexOf('</head>');
        const metaIdx = html.indexOf('<meta name="foo" content="bar">');

        expect(metaIdx).toBeLessThan(headEnd);
    });

    it('uses custom themeStorageKey', () => {
        const html = buildHtmlPage({ ...defaults, theme: 'dark', themeStorageKey: 'my-custom-key' });

        expect(html).toContain('my-custom-key');
        expect(html).not.toContain('qa-theme');
    });
});

describe('BuildThemeScript', () => {
    it('generates script with localStorage key respecting storageKey parameter', () => {
        const script = buildThemeScript('dark', 'custom-key');

        expect(script).toContain('custom-key');
        expect(script).not.toContain('qa-theme');
    });

    it('toggleTheme function uses the correct storageKey', () => {
        const script = buildThemeScript('system', 'my-theme');

        expect(script).toContain("localStorage.setItem('my-theme'");
    });

    it('defaults storageKey to qa-theme', () => {
        const script = buildThemeScript('light');

        expect(script).toContain("localStorage.setItem('qa-theme'");
    });

    it('defaults theme to system', () => {
        const script = buildThemeScript();

        expect(script).toContain("var theme = 'system'");
    });

    it('generates a script tag', () => {
        const script = buildThemeScript('dark');

        expect(script).toContain('<script');
        expect(script).toContain('</script>');
    });
});

describe('BuildErrorPage', () => {
    it('returns minimal error HTML with given label', () => {
        const html = buildErrorPage('Error', 'Something went wrong');

        expect(html).toContain('<!DOCTYPE html>');
        expect(html).toContain('<html');
        expect(html).toContain('<body>');
        expect(html).toContain('<h1>Something went wrong</h1>');
    });

    it('returns the title when no label provided', () => {
        const html = buildErrorPage('Fallback Title', '');

        expect(html).toContain('<h1>Fallback Title</h1>');
    });

    it('uses title when label is empty string', () => {
        const html = buildErrorPage('Empty Label', '');

        expect(html).toContain('<h1>Empty Label</h1>');
    });
});
