/**
 * Release Readiness Score — weighted composite of tasks, health, coverage, and flakiness.
 *
 * D1 / Sprint 10: Pure-function composition of four dimensions into a single release
 * readiness score with grade, per-dimension breakdown, and recommendation.
 *
 * @module release-score
 */

import { buildHtmlPage } from './html-factory.js';
import { buildCss } from './report-styles.js';
import { buildReleaseSection } from './report-sections.js';
import { formatDateISO } from './date-utils.js';

export interface ReleaseScoreResult {
    score: number;
    grade: string;
    breakdown: Array<{ label: string; score: number; status: 'pass' | 'fail' }>;
    recommendation: string;
    timestamp: string;
}

const TASKS_W = 0.25;
const HEALTH_W = 0.3;
const COVERAGE_W = 0.25;
const FLAKINESS_W = 0.2;

const THRESHOLD = 70;

function computeGrade(score: number): string {
    if (score >= 90) return 'excellent';
    if (score >= 70) return 'good';
    if (score >= 50) return 'needs_attention';
    return 'critical';
}

function invertFlakiness(flakyRate: number): number {
    return Math.max(0, Math.min(100, 100 - flakyRate));
}

function buildBreakdown(
    tasksPct: number,
    healthScore: number,
    healthGate: 'pass' | 'fail',
    coveragePct: number,
    flakyRate: number,
): Array<{ label: string; score: number; status: 'pass' | 'fail' }> {
    const flkScore = invertFlakiness(flakyRate);
    return [
        { label: 'Tasks', score: Math.round(tasksPct), status: tasksPct >= THRESHOLD ? 'pass' : 'fail' },
        { label: 'Health', score: Math.round(healthScore), status: healthGate },
        { label: 'Coverage', score: Math.round(coveragePct), status: coveragePct >= THRESHOLD ? 'pass' : 'fail' },
        { label: 'Flakiness', score: Math.round(flkScore), status: flkScore >= THRESHOLD ? 'pass' : 'fail' },
    ];
}

function buildRecommendation(
    tasksPct: number,
    healthScore: number,
    healthGate: 'pass' | 'fail',
    coveragePct: number,
    flakyRate: number,
): string {
    const failures: string[] = [];
    if (tasksPct < THRESHOLD) failures.push('tasks');
    if (healthGate === 'fail' || healthScore < THRESHOLD) failures.push('health');
    if (coveragePct < THRESHOLD) failures.push('coverage');
    if (invertFlakiness(flakyRate) < THRESHOLD) failures.push('flakiness');
    if (failures.length === 0) return 'All dimensions meet the release threshold. Ready for release.';
    return `Improve ${failures.join(', ')} before release.`;
}

export function calculateReleaseScore(
    tasksPct: number,
    healthScore: number,
    healthGate: 'pass' | 'fail',
    coveragePct: number,
    flakyRate: number,
): ReleaseScoreResult {
    const flkScore = invertFlakiness(flakyRate);
    const raw = tasksPct * TASKS_W + healthScore * HEALTH_W + coveragePct * COVERAGE_W + flkScore * FLAKINESS_W;
    const score = Math.round(raw);
    const grade = computeGrade(score);
    const breakdown = buildBreakdown(tasksPct, healthScore, healthGate, coveragePct, flakyRate);
    const recommendation = buildRecommendation(tasksPct, healthScore, healthGate, coveragePct, flakyRate);
    return { score, grade, breakdown, recommendation, timestamp: new Date().toISOString() };
}

export function generateReleaseScoreHtml(result: ReleaseScoreResult): string {
    const bodyContent =
        '<h1>Release Readiness Score</h1>' +
        buildReleaseSection(result.score, result.grade, result.breakdown, result.recommendation);
    return buildHtmlPage({
        title: 'Release Readiness Score',
        styles: buildCss(),
        theme: 'system',
        bodyContent,
        footer: `Generated by QA Tools · ${formatDateISO()}`,
    });
}
