/**
 * PR Report — posts an enriched test summary comment to GitHub Pull Requests.
 *
 * Reads the CTRF test report generated by the vitest CTRF reporter,
 * optionally augments with AI failure analysis, quality gate results,
 * and flaky detection data, then posts a comprehensive markdown comment
 * to the GitHub Pull Request.
 *
 * Usage:
 *   npx tsx scripts/pr-report.ts [options]
 *
 * Options:
 *   --ctrf <path>        Path to CTRF JSON file (default: reports/ctrf-report.json)
 *   --no-ai              Skip AI failure analysis (placeholder text only)
 *   --no-quality         Skip quality gate
 *   --no-flaky           Skip flaky detection
 *
 * Environment:
 *   GITHUB_TOKEN         Required for posting PR comments
 *   GITHUB_REPOSITORY    Repository in owner/repo format
 *   GITHUB_PR_NUMBER     PR number
 */

import fs from 'node:fs';
import { rootLogger } from '../shared/logger.js';
import { postPrComment } from '../shared/github-pr-comment.js';
import { parseTestResultsFile, type ParseResult } from '../shared/result_parser.js';
import { runQualityGate } from '../shared/quality-gate.js';
import { createCheckRun } from '../shared/github-check-run.js';
import { loadMetrics, calculateFlakiness } from '../shared/metrics.js';
import { isQuarantined } from '../shared/quarantine.js';

// ---------------------------------------------------------------------------
// CLI argument parsing
// ---------------------------------------------------------------------------

interface CliOptions {
    ctrfPath: string;
    skipAi: boolean;
    skipQuality: boolean;
    skipFlaky: boolean;
}

function parseArgs(args: string[]): CliOptions {
    const opts: CliOptions = {
        ctrfPath: 'reports/ctrf-report.json',
        skipAi: false,
        skipQuality: false,
        skipFlaky: false,
    };
    for (let i = 0; i < args.length; i++) {
        switch (args[i]) {
            case '--ctrf':
                opts.ctrfPath = args[++i] ?? opts.ctrfPath;
                break;
            case '--no-ai':
                opts.skipAi = true;
                break;
            case '--no-quality':
                opts.skipQuality = true;
                break;
            case '--no-flaky':
                opts.skipFlaky = true;
                break;
        }
    }
    return opts;
}

// ---------------------------------------------------------------------------
// Markdown builders
// ---------------------------------------------------------------------------

function buildSummaryTable(result: ParseResult): string {
    const { stats } = result;
    const passRate = stats.total > 0 ? ((stats.passed / stats.total) * 100).toFixed(1) : '0.0';
    const durationSec = (stats.duration / 1000).toFixed(1);

    return [
        '## 📊 Test Results',
        '',
        '| ✅ Passed | ❌ Failed | ⏭ Skipped | 📦 Total | ⏱ Duration | 📈 Pass Rate |',
        '|---|---|---|---|---|---|',
        `| ${stats.passed} | ${stats.failed} | ${stats.skipped} | ${stats.total} | ${durationSec}s | ${passRate}% |`,
        '',
    ].join('\n');
}

function buildFailureTable(result: ParseResult): string {
    const failed = result.tests.filter((t) => t.state === 'failed');
    if (failed.length === 0) return '';

    const rows = failed.map((t) => {
        const error = t.error ? t.error.replace(/\n/g, ' ').slice(0, 200) : '';
        return `| ${t.title.replace(/\|/g, '\\|')} | ${t.duration}ms | ${error.replace(/\|/g, '\\|')} |`;
    });

    const maxRows = 50;
    const truncated = rows.length > maxRows;
    const displayRows = truncated ? rows.slice(0, maxRows) : rows;

    return [
        '',
        '### ❌ Failed Tests',
        '',
        '| Test | Duration | Error |',
        '|---|---|---|',
        ...displayRows,
        ...(truncated ? [`| _... and ${rows.length - maxRows} more_ | | |`] : []),
        '',
    ].join('\n');
}

function buildQGCHeckSummary(result: {
    overall: 'pass' | 'fail';
    score: number;
    checks: Array<{ name: string; status: 'pass' | 'fail'; score: number; threshold: number }>;
}): string {
    const lines: string[] = [
        `**Quality Gate: ${result.overall === 'pass' ? '✅ PASSED' : '❌ FAILED'}**`,
        '',
        `**Score:** ${result.score}/100`,
        '',
        '| Check | Score | Threshold | Status |',
        '|---|---|---|---|',
    ];
    for (const check of result.checks) {
        const icon = check.status === 'pass' ? '✅' : '❌';
        lines.push(`| ${check.name} | ${check.score} | ${check.threshold} | ${icon} |`);
    }
    return lines.join('\n');
}

function buildQualityGateSection(result: {
    overall: 'pass' | 'fail';
    score: number;
    checks: Array<{ name: string; status: 'pass' | 'fail'; score: number; threshold: number }>;
}): string {
    const statusIcon = result.overall === 'pass' ? '✅' : '❌';
    const checkRows = result.checks.map(
        (c) => `| ${c.name} | ${c.score} | ${c.threshold} | ${c.status === 'pass' ? '✅' : '❌'} |`,
    );

    return [
        '',
        `## 🛡️ Quality Gate: ${statusIcon} ${result.overall.toUpperCase()} (Score: ${result.score}/100)`,
        '',
        '| Check | Actual | Threshold | Status |',
        '|---|---|---|---|',
        ...checkRows,
        '',
    ].join('\n');
}

function buildFlakySection(): string {
    try {
        const store = loadMetrics();
        const flakyEntries = calculateFlakiness(store, 2);
        const highFlaky = flakyEntries.filter((e) => e.rate >= 0.3);

        if (highFlaky.length === 0) return '';

        const rows = highFlaky.map((t) => {
            const quarantined = isQuarantined(t.title);
            const status = quarantined ? '🔒 Quarantined' : '⚠️ New';
            return [
                `| ${t.title.replace(/\|/g, '\\|')}`,
                `${(t.rate * 100).toFixed(0)}%`,
                `${t.passCount}/${t.totalRuns}`,
                `${status} |`,
            ].join(' | ');
        });

        const newFlaky = highFlaky.filter((t) => !isQuarantined(t.title));
        const suggestion =
            newFlaky.length > 0
                ? `\n> 💡 ${newFlaky.length} flaky test(s) not yet quarantined. Consider adding them to quarantine to reduce CI noise.\n`
                : '';

        return [
            '',
            '## ⚠️ Flaky Tests (rate ≥ 30%)',
            '',
            '| Test | Flaky Rate | Passed/Total | Quarantine |',
            '|---|---|---|---|',
            ...rows,
            suggestion,
            '',
        ].join('\n');
    } catch {
        return '';
    }
}

function buildAiAnalysisSection(): string {
    return [
        '',
        '### 🤖 AI Failure Analysis',
        '',
        'AI-powered failure analysis with classification, self-consistency, and attribution ',
        'is available when LLM is configured (`LLM_API_KEY`).',
        '',
    ].join('\n');
}

function buildFooter(): string {
    const penv = process.env as Record<string, string | undefined>;
    const ghServer = penv['GITHUB_SERVER_URL'];
    const ghRepo = penv['GITHUB_REPOSITORY'];
    const ghRunId = penv['GITHUB_RUN_ID'];
    const workflowUrl = ghServer && ghRepo && ghRunId ? `${ghServer}/${ghRepo}/actions/runs/${ghRunId}` : undefined;

    const artifactUrl = workflowUrl ? `${workflowUrl}?pr=1#artifacts` : undefined;

    const parts: string[] = ['---', ''];

    if (workflowUrl) {
        parts.push(`🔍 [View workflow run](${workflowUrl})`);
        if (artifactUrl) {
            parts.push(`📄 [Download HTML report](${artifactUrl})`);
        }
    }
    parts.push(`_Generated at ${new Date().toISOString()}_`);
    parts.push('');

    return parts.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export async function main(): Promise<void> {
    const opts = parseArgs(process.argv.slice(2));

    // Read and parse CTRF report
    if (!fs.existsSync(opts.ctrfPath)) {
        rootLogger.warn(`CTRF report not found: ${opts.ctrfPath}. Skipping PR comment.`);
        process.exit(0);
    }

    const result = parseTestResultsFile(opts.ctrfPath);
    if (result.error) {
        rootLogger.warn(`Error parsing CTRF report: ${result.error}. Skipping PR comment.`);
        process.exit(0);
    }

    const sections: string[] = [];

    // 1. Summary table
    sections.push(buildSummaryTable(result));

    // 2. Failed tests table
    const failSection = buildFailureTable(result);
    if (failSection) sections.push(failSection);

    // 3. AI analysis (unless skipped)
    if (!opts.skipAi) {
        sections.push(buildAiAnalysisSection());
    }

    // 4. Quality gate (unless skipped)
    if (!opts.skipQuality) {
        let qgResult: ReturnType<typeof runQualityGate> | null = null;
        try {
            qgResult = runQualityGate();
        } catch {
            /* runQualityGate will handle its own errors */
        }

        if (qgResult) {
            sections.push(buildQualityGateSection(qgResult));

            // Create a Check Run on the commit for the quality gate result
            await createCheckRun({
                name: 'Quality Gate',
                status: 'completed',
                conclusion: qgResult.overall === 'pass' ? 'success' : 'failure',
                output: {
                    title: `Quality Gate: ${qgResult.overall.toUpperCase()} (Score: ${qgResult.score}/100)`,
                    summary: buildQGCHeckSummary(qgResult),
                },
            });
        }
    }

    // 5. Flaky detection (unless skipped)
    if (!opts.skipFlaky) {
        const flakySection = buildFlakySection();
        if (flakySection) sections.push(flakySection);
    }

    // 6. Footer
    sections.push(buildFooter());

    const commentBody = sections.join('\n');

    // Post to PR
    const resultPost = await postPrComment(commentBody);
    if (resultPost) {
        rootLogger.info(`PR report posted: ${resultPost.html_url}`);
    } else {
        rootLogger.info('PR comment not posted (required env vars missing, or running outside PR context)');
    }
}

if (!process.env['VITEST'] && process.argv[1]?.includes('pr-report')) {
    main().catch((err) => {
        rootLogger.error(`pr-report failed: ${err instanceof Error ? err.message : String(err)}`);
        process.exit(1);
    });
}
