/**
 * PR Report — posts an enriched test summary comment to GitHub Pull Requests.
 *
 * Reads the CTRF test report generated by the vitest CTRF reporter,
 * optionally augments with AI failure analysis, quality gate results,
 * and flaky detection data, then posts a comprehensive markdown comment
 * to the GitHub Pull Request.
 *
 * Usage:
 *   npx tsx scripts/pr-report.ts [options]
 *
 * Options:
 *   --ctrf <path>        Path to CTRF JSON file (default: reports/ctrf-report.json)
 *   --no-ai              Skip AI failure analysis (placeholder text only)
 *   --no-quality         Skip quality gate
 *   --no-flaky           Skip flaky detection
 *
 * Environment:
 *   GITHUB_TOKEN         Required for posting PR comments
 *   GITHUB_REPOSITORY    Repository in owner/repo format
 *   GITHUB_PR_NUMBER     PR number
 *
 * Generates a full HTML report (shared/report-html.ts) with 28+ health
 * information points, uploaded as a CI artifact for download.
 */

import fs from 'node:fs';
import { rootLogger } from '../shared/logger.js';
import { postPrComment } from '../shared/github-pr-comment.js';
import { parseTestResultsFile, type ParseResult, type FlatTest } from '../shared/result_parser.js';
import { runQualityGate } from '../shared/quality-gate.js';
import { createCheckRun } from '../shared/github-check-run.js';
import { loadMetrics, calculateFlakiness, getTrends } from '../shared/metrics.js';
import { isQuarantined } from '../shared/quarantine.js';
import { generateHtmlReport } from '../shared/report-html.js';
import type { ReportOptions } from '../shared/report-types.js';
import { calculateHealthScore } from '../shared/health-score.js';

// ---------------------------------------------------------------------------
// CLI argument parsing
// ---------------------------------------------------------------------------

interface CliOptions {
    ctrfPath: string;
    skipAi: boolean;
    skipQuality: boolean;
    skipFlaky: boolean;
}

function parseArgs(args: string[]): CliOptions {
    const opts: CliOptions = {
        ctrfPath: 'reports/ctrf-report.json',
        skipAi: false,
        skipQuality: false,
        skipFlaky: false,
    };
    for (let i = 0; i < args.length; i++) {
        switch (args[i]) {
            case '--ctrf':
                opts.ctrfPath = args[++i] ?? opts.ctrfPath;
                break;
            case '--no-ai':
                opts.skipAi = true;
                break;
            case '--no-quality':
                opts.skipQuality = true;
                break;
            case '--no-flaky':
                opts.skipFlaky = true;
                break;
        }
    }
    return opts;
}

// ---------------------------------------------------------------------------
// Diff comparison helpers
// ---------------------------------------------------------------------------

interface DiffComparison {
    newFailures: FlatTest[];
    newPasses: FlatTest[];
    flaky: FlatTest[];
}

/** Compare current test run against a previous run, returning new failures, fixes, and flaky tests. */
function computeDiffComparison(current: FlatTest[], previous: FlatTest[]): DiffComparison | undefined {
    if (previous.length === 0) return undefined;

    const prevByTitle = new Map<string, FlatTest>();
    for (const t of previous) {
        prevByTitle.set(t.title, t);
    }

    const currByTitle = new Map<string, FlatTest>();
    for (const t of current) {
        currByTitle.set(t.title, t);
    }

    const newFailures: FlatTest[] = [];
    const newPasses: FlatTest[] = [];
    const flaky: FlatTest[] = [];

    for (const [title, test] of currByTitle) {
        const prev = prevByTitle.get(title);
        if (!prev) continue;

        const currFailed = test.state === 'failed';
        const prevFailed = prev.state === 'failed';

        if (currFailed && !prevFailed) {
            newFailures.push(test);
        } else if (!currFailed && prevFailed) {
            newPasses.push(test);
        }

        if (test.state !== prev.state) {
            flaky.push(test);
        }
    }

    if (newFailures.length === 0 && newPasses.length === 0 && flaky.length === 0) {
        return undefined;
    }

    return { newFailures, newPasses, flaky };
}

// ---------------------------------------------------------------------------
// Markdown builders
// ---------------------------------------------------------------------------

function buildSummaryTable(result: ParseResult): string {
    const { stats } = result;
    const passRate = stats.total > 0 ? ((stats.passed / stats.total) * 100).toFixed(1) : '0.0';
    const durationSec = (stats.duration / 1000).toFixed(1);

    return [
        '## 📊 Test Results',
        '',
        '| ✅ Passed | ❌ Failed | ⏭ Skipped | 📦 Total | ⏱ Duration | 📈 Pass Rate |',
        '|---|---|---|---|---|---|',
        `| ${stats.passed} | ${stats.failed} | ${stats.skipped} | ${stats.total} | ${durationSec}s | ${passRate}% |`,
        '',
    ].join('\n');
}

function buildFailureTable(result: ParseResult): string {
    const failed = result.tests.filter((t) => t.state === 'failed');
    if (failed.length === 0) return '';

    const rows = failed.map((t) => {
        const error = t.error ? t.error.replace(/\n/g, ' ').slice(0, 200) : '';
        return `| ${t.title.replace(/\|/g, '\\|')} | ${t.duration}ms | ${error.replace(/\|/g, '\\|')} |`;
    });

    const maxRows = 50;
    const truncated = rows.length > maxRows;
    const displayRows = truncated ? rows.slice(0, maxRows) : rows;

    return [
        '',
        '### ❌ Failed Tests',
        '',
        '| Test | Duration | Error |',
        '|---|---|---|',
        ...displayRows,
        ...(truncated ? [`| _... and ${rows.length - maxRows} more_ | | |`] : []),
        '',
    ].join('\n');
}

function buildQGCHeckSummary(
    result: {
        overall: 'pass' | 'fail';
        score: number;
        checks: Array<{ name: string; status: 'pass' | 'fail'; score: number; threshold: number }>;
    },
    grade?: string,
): string {
    const lines: string[] = [
        `**Quality Gate: ${result.overall === 'pass' ? '✅ PASSED' : '❌ FAILED'}**`,
        '',
        `**Score:** ${result.score}/100`,
    ];
    if (grade) {
        lines.push(`**Grade:** ${grade}`);
    }
    lines.push('', '| Check | Score | Threshold | Status |', '|---|---|---|---|');
    for (const check of result.checks) {
        const icon = check.status === 'pass' ? '✅' : '❌';
        lines.push(`| ${check.name} | ${check.score} | ${check.threshold} | ${icon} |`);
    }
    lines.push('', '📄 [Download HTML report](#artifacts)');
    return lines.join('\n');
}

function buildQualityGateSection(result: {
    overall: 'pass' | 'fail';
    score: number;
    checks: Array<{ name: string; status: 'pass' | 'fail'; score: number; threshold: number }>;
}): string {
    const statusIcon = result.overall === 'pass' ? '✅' : '❌';
    const checkRows = result.checks.map(
        (c) => `| ${c.name} | ${c.score} | ${c.threshold} | ${c.status === 'pass' ? '✅' : '❌'} |`,
    );

    return [
        '',
        `## 🛡️ Quality Gate: ${statusIcon} ${result.overall.toUpperCase()} (Score: ${result.score}/100)`,
        '',
        '| Check | Actual | Threshold | Status |',
        '|---|---|---|---|',
        ...checkRows,
        '',
    ].join('\n');
}

function buildFlakySection(): string {
    try {
        const store = loadMetrics();
        const flakyEntries = calculateFlakiness(store, 2);
        const highFlaky = flakyEntries.filter((e) => e.rate >= 0.3);

        if (highFlaky.length === 0) return '';

        const rows = highFlaky.map((t) => {
            const quarantined = isQuarantined(t.title);
            const status = quarantined ? '🔒 Quarantined' : '⚠️ New';
            return [
                `| ${t.title.replace(/\|/g, '\\|')}`,
                `${(t.rate * 100).toFixed(0)}%`,
                `${t.passCount}/${t.totalRuns}`,
                `${status} |`,
            ].join(' | ');
        });

        const newFlaky = highFlaky.filter((t) => !isQuarantined(t.title));
        const suggestion =
            newFlaky.length > 0
                ? `\n> 💡 ${newFlaky.length} flaky test(s) not yet quarantined. Consider adding them to quarantine to reduce CI noise.\n`
                : '';

        return [
            '',
            '## ⚠️ Flaky Tests (rate ≥ 30%)',
            '',
            '| Test | Flaky Rate | Passed/Total | Quarantine |',
            '|---|---|---|---|',
            ...rows,
            suggestion,
            '',
        ].join('\n');
    } catch {
        return '';
    }
}

function buildAiAnalysisSection(): string {
    return [
        '',
        '### 🤖 AI Failure Analysis',
        '',
        'AI-powered failure analysis with classification, self-consistency, and attribution ',
        'is available when LLM is configured (`LLM_API_KEY`).',
        '',
    ].join('\n');
}

function buildFooter(): string {
    const penv = process.env as Record<string, string | undefined>;
    const ghServer = penv['GITHUB_SERVER_URL'];
    const ghRepo = penv['GITHUB_REPOSITORY'];
    const ghRunId = penv['GITHUB_RUN_ID'];
    const workflowUrl = ghServer && ghRepo && ghRunId ? `${ghServer}/${ghRepo}/actions/runs/${ghRunId}` : undefined;

    const artifactUrl = workflowUrl ? `${workflowUrl}?pr=1#artifacts` : undefined;

    const parts: string[] = ['---', ''];

    if (workflowUrl) {
        parts.push(`🔍 [View workflow run](${workflowUrl})`);
        if (artifactUrl) {
            parts.push(`📄 [Download HTML report](${artifactUrl})`);
        }
    }
    parts.push(`_Generated at ${new Date().toISOString()}_`);
    parts.push('');

    return parts.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export async function main(): Promise<void> {
    const opts = parseArgs(process.argv.slice(2));

    // Read and parse CTRF report
    if (!fs.existsSync(opts.ctrfPath)) {
        rootLogger.warn(`CTRF report not found: ${opts.ctrfPath}. Skipping PR comment.`);
        process.exit(0);
    }

    const result = parseTestResultsFile(opts.ctrfPath);
    if (result.error) {
        rootLogger.warn(`Error parsing CTRF report: ${result.error}. Skipping PR comment.`);
        process.exit(0);
    }

    // Load metrics store once for health score, trends, flaky, and diff comparison
    const store = loadMetrics();
    const healthScore = calculateHealthScore(store, {});
    const trends = getTrends(store);

    // Compute diff comparison against the most recent run in the metrics store
    const previousRun = store.runs.length > 0 ? store.runs[store.runs.length - 1] : undefined;
    const diffComparison = previousRun ? computeDiffComparison(result.tests, previousRun.tests) : undefined;

    const sections: string[] = [];

    // 1. Summary table
    sections.push(buildSummaryTable(result));

    // 2. Failed tests table
    const failSection = buildFailureTable(result);
    if (failSection) sections.push(failSection);

    // 3. AI analysis (unless skipped)
    if (!opts.skipAi) {
        sections.push(buildAiAnalysisSection());
    }

    // 4. Quality gate (unless skipped)
    if (!opts.skipQuality) {
        let qgResult: ReturnType<typeof runQualityGate> | null = null;
        try {
            qgResult = runQualityGate();
        } catch {
            /* runQualityGate handles its own errors */
        }

        if (qgResult) {
            sections.push(buildQualityGateSection(qgResult));

            // Build expanded Check Run summary with grade + artifact link
            const gradeStr = healthScore.grade.replace(/_/g, ' ').toUpperCase();
            const checkSummary = buildQGCHeckSummary(qgResult, gradeStr);

            // Create a Check Run on the commit for the quality gate result
            await createCheckRun({
                name: 'Quality Gate',
                status: 'completed',
                conclusion: qgResult.overall === 'pass' ? 'success' : 'failure',
                output: {
                    title: `Quality Gate: ${qgResult.overall.toUpperCase()} (Score: ${qgResult.score}/100) | Grade: ${gradeStr}`,
                    summary: checkSummary,
                },
            });
        }
    }

    // 5. Flaky detection (unless skipped)
    if (!opts.skipFlaky) {
        const flakySection = buildFlakySection();
        if (flakySection) sections.push(flakySection);
    }

    // 6. Generate full HTML report with health score, trends, diff, and flakiness
    const ghServer = process.env['GITHUB_SERVER_URL'];
    const ghRepo = process.env['GITHUB_REPOSITORY'];
    const ghRunId = process.env['GITHUB_RUN_ID'];
    const ghBranch = process.env['GITHUB_REF_NAME'];
    const workflowUrl = ghServer && ghRepo && ghRunId ? `${ghServer}/${ghRepo}/actions/runs/${ghRunId}` : undefined;

    const passRate = result.stats.total > 0 ? (result.stats.passed / result.stats.total) * 100 : 0;

    // Build flakiness map for the HTML report
    const flakyEntries = calculateFlakiness(store, 2);
    const flakinessMap: Record<string, number> = {};
    for (const entry of flakyEntries) {
        flakinessMap[entry.title] = entry.rate;
    }

    const htmlOptions: ReportOptions = {
        title: `QA Tools — PR Report${ghBranch ? ` (${ghBranch})` : ''}`,
        qualityGate: Math.round(passRate),
        healthScore,
        trends,
        includeChart: true,
        ...(workflowUrl ? { ciUrl: workflowUrl } : {}),
        ...(ghBranch ? { branch: ghBranch } : {}),
        ...(Object.keys(flakinessMap).length > 0 ? { flakinessMap } : {}),
        ...(diffComparison ? { diffComparison } : {}),
    };

    const html = generateHtmlReport(result.tests, htmlOptions);
    fs.mkdirSync('reports', { recursive: true });
    fs.writeFileSync('reports/pr-report.html', html, 'utf8');
    rootLogger.info(`HTML report generated: reports/pr-report.html (${html.length} bytes)`);

    // 7. Footer
    sections.push(buildFooter());

    const commentBody = sections.join('\n');

    // Post to PR
    const resultPost = await postPrComment(commentBody);
    if (resultPost) {
        rootLogger.info(`PR report posted: ${resultPost.html_url}`);
    } else {
        rootLogger.info('PR comment not posted (required env vars missing, or running outside PR context)');
    }
}

if (!process.env['VITEST'] && process.argv[1]?.includes('pr-report')) {
    main().catch((err) => {
        rootLogger.error(`pr-report failed: ${err instanceof Error ? err.message : String(err)}`);
        process.exit(1);
    });
}
