import fs from 'fs';
import path from 'path';
import type { SetupContext } from './context';

interface WriterResult {
    filesCreated: string[];
    filesSkipped: string[];
}

export function writeProjectsConfig(
    ctx: Pick<SetupContext, 'projectName' | 'gitProvider' | 'repoName' | 'repoOwner'>,
): WriterResult {
    const result: WriterResult = { filesCreated: [], filesSkipped: [] };
    const configDir = path.resolve(process.cwd(), 'config');
    fs.mkdirSync(configDir, { recursive: true });

    const projectsPath = path.join(configDir, 'projects.json');
    if (fs.existsSync(projectsPath)) {
        try {
            const existing = JSON.parse(fs.readFileSync(projectsPath, 'utf8')) as Record<string, unknown>;
            if (ctx.projectName in existing) {
                result.filesSkipped.push(projectsPath);
            } else {
                existing[ctx.projectName] = ctx.gitProvider === 'github' ? ctx.repoName : ctx.projectName;
                fs.writeFileSync(projectsPath, JSON.stringify(existing, null, 2) + '\n', 'utf8');
                result.filesCreated.push(projectsPath);
            }
        } catch {
            fs.writeFileSync(
                projectsPath,
                JSON.stringify({ [ctx.projectName]: ctx.projectName }, null, 2) + '\n',
                'utf8',
            );
            result.filesCreated.push(projectsPath);
        }
    } else {
        const id = ctx.gitProvider === 'github' ? ctx.repoName : ctx.projectName;
        fs.writeFileSync(projectsPath, JSON.stringify({ [ctx.projectName]: id }, null, 2) + '\n', 'utf8');
        result.filesCreated.push(projectsPath);
    }

    const providersPath = path.join(configDir, 'providers.json');
    const providerEntry =
        ctx.gitProvider === 'github'
            ? { provider: 'github', repo: ctx.repoOwner + '/' + ctx.repoName }
            : { provider: 'gitlab' };

    if (fs.existsSync(providersPath)) {
        try {
            const existing = JSON.parse(fs.readFileSync(providersPath, 'utf8')) as Record<string, unknown>;
            if (ctx.projectName in existing) {
                result.filesSkipped.push(providersPath);
            } else {
                existing[ctx.projectName] = providerEntry;
                fs.writeFileSync(providersPath, JSON.stringify(existing, null, 2) + '\n', 'utf8');
                result.filesCreated.push(providersPath);
            }
        } catch {
            fs.writeFileSync(
                providersPath,
                JSON.stringify({ [ctx.projectName]: providerEntry }, null, 2) + '\n',
                'utf8',
            );
            result.filesCreated.push(providersPath);
        }
    } else {
        fs.writeFileSync(providersPath, JSON.stringify({ [ctx.projectName]: providerEntry }, null, 2) + '\n', 'utf8');
        result.filesCreated.push(providersPath);
    }

    return result;
}

export function writeDotEnvExample(ctx: Pick<SetupContext, 'projectName' | 'gitProvider'>): WriterResult {
    const result: WriterResult = { filesCreated: [], filesSkipped: [] };
    const envPath = path.resolve(process.cwd(), '.env.example');

    const lines: string[] = [];
    if (ctx.gitProvider === 'github') {
        lines.push('# GitHub Token (criar em https://github.com/settings/tokens)');
        lines.push('GITHUB_TOKEN=');
    } else {
        lines.push('# GitLab Token (criar em https://gitlab.com/-/user_settings/personal_access_tokens)');
        lines.push('GIT_TOKEN=');
        lines.push('GIT_BASE_URL=https://gitlab.com');
    }
    lines.push('');
    lines.push('# Jira');
    lines.push('JIRA_BASE_URL=https://seu-jira.atlassian.net');
    lines.push('JIRA_TOKEN=');
    lines.push('JIRA_USER_EMAIL=email@exemplo.com');
    lines.push('');
    lines.push('# QA Tools');
    lines.push('QA_TOOLS_LOGS_DIR=./logs');
    lines.push('QA_FAIL_ON=80');

    if (fs.existsSync(envPath)) {
        result.filesSkipped.push(envPath);
    } else {
        fs.writeFileSync(envPath, lines.join('\n') + '\n', 'utf8');
        result.filesCreated.push(envPath);
    }

    return result;
}

export function writePrePushHook(ctx: Pick<SetupContext, 'projectName'>): WriterResult {
    const result: WriterResult = { filesCreated: [], filesSkipped: [] };
    const hookDir = path.resolve(process.cwd(), '.git', 'hooks');
    fs.mkdirSync(hookDir, { recursive: true });

    const hookPath = path.join(hookDir, 'pre-push');
    if (fs.existsSync(hookPath)) {
        result.filesSkipped.push(hookPath);
        return result;
    }

    const script = `#!/bin/sh
# QA Tools pre-push hook — generated by setup/main.ts
# Execute tests before push, block if failures found.

echo "🔍 QA Tools: Running tests before push..."
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

npx tsx git_triggers/main.ts --batch --project ${ctx.projectName} --branch "$CURRENT_BRANCH"
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ QA Tools: Tests failed. Push blocked."
    echo "   Fix the failures or use 'git push --no-verify' to bypass."
    exit 1
fi

echo "✅ QA Tools: All checks passed."
exit 0
`;

    fs.writeFileSync(hookPath, script, 'utf8');
    fs.chmodSync(hookPath, 0o755);
    result.filesCreated.push(hookPath);
    return result;
}
