import fs from 'fs';
import path from 'path';
import type { SetupContext } from './context.js';
import { setPrReportConfig } from '../shared/feature-config.js';

interface WriterResult {
    filesCreated: string[];
    filesSkipped: string[];
}

type ConfigCtx = Pick<SetupContext, 'projectName' | 'gitProvider' | 'repoName' | 'repoOwner'>;

function writeJsonConfig(
    filePath: string,
    ctx: ConfigCtx,
    makeEntry: (ctx: ConfigCtx) => unknown,
    result: WriterResult,
): void {
    if (!fs.existsSync(filePath)) {
        fs.writeFileSync(filePath, JSON.stringify({ [ctx.projectName]: makeEntry(ctx) }, null, 2) + '\n', 'utf8');
        result.filesCreated.push(filePath);
        return;
    }
    try {
        const existing = JSON.parse(fs.readFileSync(filePath, 'utf8')) as Record<string, unknown>;
        if (ctx.projectName in existing) {
            result.filesSkipped.push(filePath);
        } else {
            existing[ctx.projectName] = makeEntry(ctx);
            fs.writeFileSync(filePath, JSON.stringify(existing, null, 2) + '\n', 'utf8');
            result.filesCreated.push(filePath);
        }
    } catch {
        fs.writeFileSync(filePath, JSON.stringify({ [ctx.projectName]: makeEntry(ctx) }, null, 2) + '\n', 'utf8');
        result.filesCreated.push(filePath);
    }
}

function makeProjectEntry(ctx: ConfigCtx): unknown {
    return ctx.gitProvider === 'github' ? ctx.repoName : ctx.projectName;
}

function makeProviderEntry(ctx: ConfigCtx): unknown {
    return ctx.gitProvider === 'github'
        ? { provider: 'github', repo: ctx.repoOwner + '/' + ctx.repoName }
        : { provider: 'gitlab' };
}

function ensureConfigDir(): string {
    const configDir = path.resolve(process.cwd(), 'config');
    fs.mkdirSync(configDir, { recursive: true });
    return configDir;
}

export function writeProjectsConfig(
    ctx: ConfigCtx,
): WriterResult {
    const result: WriterResult = { filesCreated: [], filesSkipped: [] };
    const configDir = ensureConfigDir();

    writeJsonConfig(path.join(configDir, 'projects.json'), ctx, makeProjectEntry, result);
    writeJsonConfig(path.join(configDir, 'providers.json'), ctx, makeProviderEntry, result);

    return result;
}

export function writeDotEnvExample(ctx: Pick<SetupContext, 'projectName' | 'gitProvider'>): WriterResult {
    const result: WriterResult = { filesCreated: [], filesSkipped: [] };
    const envPath = path.resolve(process.cwd(), '.env.example');

    const lines: string[] = [];
    if (ctx.gitProvider === 'github') {
        lines.push('# GitHub Token (criar em https://github.com/settings/tokens)');
        lines.push('GITHUB_TOKEN=');
    } else {
        lines.push('# GitLab Token (criar em https://gitlab.com/-/user_settings/personal_access_tokens)');
        lines.push('GIT_TOKEN=');
        lines.push('GIT_BASE_URL=https://gitlab.com');
    }
    lines.push('');
    lines.push('# Jira');
    lines.push('JIRA_BASE_URL=https://seu-jira.atlassian.net');
    lines.push('JIRA_PERSONAL_TOKEN=');
    lines.push('JIRA_USER_EMAIL=email@exemplo.com');
    lines.push('');
    lines.push('# QA Tools');
    lines.push('QA_TOOLS_LOGS_DIR=./logs');
    lines.push('QA_FAIL_ON=80');

    if (fs.existsSync(envPath)) {
        result.filesSkipped.push(envPath);
    } else {
        fs.writeFileSync(envPath, lines.join('\n') + '\n', 'utf8');
        result.filesCreated.push(envPath);
    }

    return result;
}

export function writePrePushHook(ctx: Pick<SetupContext, 'projectName'>): WriterResult {
    const result: WriterResult = { filesCreated: [], filesSkipped: [] };
    const hookDir = path.resolve(process.cwd(), '.git', 'hooks');
    fs.mkdirSync(hookDir, { recursive: true });

    const hookPath = path.join(hookDir, 'pre-push');
    if (fs.existsSync(hookPath)) {
        result.filesSkipped.push(hookPath);
        return result;
    }

    const script = `#!/bin/sh
# QA Tools pre-push hook — generated by setup/main.ts
# Execute tests before push, block if failures found.

echo "🔍 QA Tools: Running tests before push..."
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

npx tsx git_triggers/main.ts --batch --project ${ctx.projectName} --branch "$CURRENT_BRANCH"
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ QA Tools: Tests failed. Push blocked."
    echo "   Fix the failures or use 'git push --no-verify' to bypass."
    exit 1
fi

echo "✅ QA Tools: All checks passed."
exit 0
`;

    fs.writeFileSync(hookPath, script, 'utf8');
    fs.chmodSync(hookPath, 0o755);
    result.filesCreated.push(hookPath);
    return result;
}

export function writeFeaturesConfig(ctx: SetupContext): WriterResult {
    const result: WriterResult = { filesCreated: [], filesSkipped: [] };
    if (!ctx.features.prReport) {
        return result;
    }
    setPrReportConfig(ctx.projectName, {
        enabled: true,
        publishTarget: ctx.features.prReportPublishTarget as 'github-actions' | 'gitlab-ci',
        // Persist skip flags — when feature is disabled, skip it in runtime
        skipAi: !ctx.features.aiFailureAnalysis,
        skipQuality: !ctx.features.qualityGate,
        skipFlaky: !ctx.features.flakinessDashboard,
    });
    result.filesCreated.push('config/features.json');
    return result;
}
