name: Publish to npm

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'
                  cache: npm
            - run: npm ci
            - run: npx tsc --noEmit
            - run: npx eslint . --ext .ts
            - run: npx jest --coverage --forceExit --detectOpenHandles --runInBand
            - run: npx tsc -p tsconfig.build.json
            - name: Publish
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
